#!/usr/bin/env python3
"""
Table of Contents for Relief Society Magazine Volumes 10, 11, and 12
(1923, 1924, 1925).

Extracted from the CONTENTS sections at the top of each monthly issue file.

Format: VOL{N}_TOC[(volume, issue_key)] = [entry_list]
Each entry has:
  - title: canonical title text (page numbers stripped)
  - author: author name if listed, else None
  - etype: "article", "editorial", "poem", "lesson", "report", "fiction"
"""

# ===================================================================
# VOLUME 10 (1923)
# ===================================================================

VOL10_TOC = {
    ("Vol10", "No1_January_1923"): [
        {"title": "General Board of Relief Society", "author": None, "etype": "article"},
        {"title": "Happy New Year", "author": "Lucy May Green", "etype": "poem"},
        {"title": "The New Year", "author": None, "etype": "article"},
        {"title": "Good-bye Old Year", "author": "Alveretta S. Engar", "etype": "poem"},
        {"title": "Another Woman for the Hall of Fame", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "Amy Brown Lyman Elected to State Legislature", "author": "Dr. George W. Middleton", "etype": "article"},
        {"title": "National Council of Women", "author": None, "etype": "article"},
        {"title": "The Bringing Round of Mr. Thompson", "author": "Venice F. Anderson", "etype": "fiction"},
        {"title": "Relief Society Nurse Aids' Course", "author": "Emma A. Empey", "etype": "article"},
        {"title": "President Clarissa S. Williams Visits Mexico", "author": None, "etype": "article"},
        {"title": "Conventions and Conferences", "author": None, "etype": "article"},
        {"title": "Dairy Products and Public Welfare", "author": "Fred W. Merrill", "etype": "article"},
        {"title": "A Trusting Heart", "author": "Hazel S. Washburn", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "How not to Catch Cold", "author": None, "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Editorial, Serving in a Humble Sphere", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons for March", "author": None, "etype": "lesson"},
    ],

    ("Vol10", "No2_February_1923"): [
        {"title": "Susan B. Anthony, Lucretia Mott, and Mrs. W. H. Felston", "author": None, "etype": "article"},
        {"title": "Pagan Hearts", "author": "Laura F. Crane", "etype": "fiction"},
        {"title": "From the Curtained Alcove to the United States Senate", "author": "Annie Wells Cannon", "etype": "article"},
        {"title": "Relief Society Annual Day", "author": None, "etype": "article"},
        {"title": "The Robins' Return", "author": "Myron E. Crandall, Jr.", "etype": "poem"},
        {"title": "Little Mother", "author": "Annie D. Palmer", "etype": "fiction"},
        {"title": "Grower", "author": "Mary E. Connelly", "etype": "poem"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Clarissa A. Beesley", "author": None, "etype": "article"},
        {"title": "Tuskegee Institute Health Program", "author": None, "etype": "article"},
        {"title": "One Reason for Being Convinced", "author": "Thomas L. Martin", "etype": "article"},
        {"title": "An Evening Lullaby", "author": "Julia Farr", "etype": "poem"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "report"},
    ],

    ("Vol10", "No3_March_1923"): [
        {"title": "Jane Snyder Richards", "author": None, "etype": "article"},
        {"title": "Jane Snyder Richards", "author": "Myron E. Crandall, Jr.", "etype": "article"},
        {"title": "Minutes of First Stake Relief Society Meeting", "author": None, "etype": "article"},
        {"title": "Hearsay Evidence", "author": None, "etype": "article"},
        {"title": "Amy Whipple", "author": None, "etype": "article"},
        {"title": "Lillian Cameron Released from Board", "author": None, "etype": "article"},
        {"title": "Transformation", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "A Social Conscience", "author": "Laura F. Crane", "etype": "article"},
        {"title": "Two Favorite Hymns", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "Songs for Relief Society Day", "author": None, "etype": "article"},
        {"title": "Statewide Clean-Up Campaign", "author": None, "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Anti-Narcotic Movement", "author": None, "etype": "article"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Some Firsts in Woman's Progress", "author": None, "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "New Editors for Magazine Appointed", "author": None, "etype": "article"},
        {"title": "Guide Lessons for May", "author": None, "etype": "lesson"},
    ],

    ("Vol10", "No4_April_1923"): [
        {"title": "Clarissa Smith Williams and Alice L. Reynolds", "author": None, "etype": "article"},
        {"title": "Treasured Works", "author": "Lula Greene Richards", "etype": "poem"},
        {"title": "Announcement", "author": None, "etype": "article"},
        {"title": "Mary E. Connelly", "author": None, "etype": "article"},
        {"title": "Alice Louise Reynolds", "author": "Alfred Osmond", "etype": "article"},
        {"title": "A Tribute", "author": "James L. Barker", "etype": "article"},
        {"title": "Ellen Thornycroft Fowler (Mrs. Felkins)", "author": None, "etype": "article"},
        {"title": "Women Presiding in Latter-day Saint Temples", "author": None, "etype": "article"},
        {"title": "The Revolt of Grandma Davis", "author": "Elsie C. Carroll", "etype": "fiction"},
        {"title": "The Thirteen Mistakes in Life", "author": None, "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Maude Adams", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "National Garden Week", "author": None, "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
    ],

    ("Vol10", "No5_May_1923"): [
        {"title": "The Mother", "author": None, "etype": "article"},
        {"title": "The Mocking Bird", "author": "Annie Pike Greenwood", "etype": "poem"},
        {"title": "A Mother's Love", "author": "M. L. White", "etype": "poem"},
        {"title": "The Mother, By James MacNeil Whistler", "author": "Henry Turner Bailey", "etype": "article"},
        {"title": "Mother", "author": "Claire Stewart Boyer", "etype": "poem"},
        {"title": "Mothers", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "To Father and Mother", "author": "Myron E. Crandall, Jr.", "etype": "poem"},
        {"title": "Her Daughter's Friend", "author": "Elsie Talmage Brandley", "etype": "fiction"},
        {"title": "Aunt Sally's Criticism of Mothers' Day", "author": "Joseph H. Dean", "etype": "article"},
        {"title": "Love's Alchemy", "author": "Coral J. Black", "etype": "poem"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Presidents' Day", "author": None, "etype": "article"},
        {"title": "\"Aunt Em's\" Birthday", "author": None, "etype": "article"},
        {"title": "Optimism", "author": None, "etype": "article"},
        {"title": "What Is a Vitamine?", "author": "Fred W. Merrill", "etype": "article"},
        {"title": "Tobacco", "author": "Dr. Thomas L. Martin", "etype": "article"},
        {"title": "In Memoriam", "author": None, "etype": "article"},
        {"title": "Teachers' Topic for July", "author": None, "etype": "lesson"},
        {"title": "Mary Schenck Woolman", "author": None, "etype": "article"},
        {"title": "Editorials", "author": None, "etype": "editorial"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for July", "author": None, "etype": "lesson"},
    ],

    ("Vol10", "No6_June_1923"): [
        {"title": "The Sacred Falls of Kaliuwaa, Hawaii", "author": None, "etype": "article"},
        {"title": "A Joy-Crowned Visitor", "author": "Minnie Iverson Hoddapp", "etype": "article"},
        {"title": "\"Aloha\" Garlands", "author": "Minnie Iverson Hoddapp", "etype": "article"},
        {"title": "The Relief Society Conference Minutes", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Editorial, The Divinity of Jesus Christ", "author": None, "etype": "editorial"},
        {"title": "Teachers' Topic for July", "author": None, "etype": "lesson"},
        {"title": "Relief Society Delegates Attend Conventions", "author": None, "etype": "article"},
    ],

    ("Vol10", "No7_July_1923"): [
        {"title": "The Sisters, Lydia A. Wells, Susan A. Wells", "author": None, "etype": "article"},
        {"title": "Aunt Lydia Ann and Aunt Susan A. Wells Their Testimonies", "author": "Lula Greene Richards", "etype": "article"},
        {"title": "Pioneer Sisters of 1848", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "The Pioneer", "author": "Alberta Huish", "etype": "poem"},
        {"title": "Provo's First Goddess of Liberty", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "Editorial, Faith in Our National Government", "author": None, "etype": "editorial"},
        {"title": "The Palace of Peace", "author": "Annie D. Palmer", "etype": "fiction"},
        {"title": "Conservation of Time and Energy With and Without the Home", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Items About Women", "author": None, "etype": "article"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for September", "author": None, "etype": "lesson"},
    ],

    ("Vol10", "No8_August_1923"): [
        {"title": "Timpanogos Climbed to the Top in Winter", "author": None, "etype": "article"},
        {"title": "Utah Mountains", "author": None, "etype": "article"},
        {"title": "Eliza Roxey Snow Memorial", "author": None, "etype": "article"},
        {"title": "What Utah Does for the Deaf", "author": "Amy Whipple Evans", "etype": "article"},
        {"title": "The Value of a Smile", "author": "Alta Wellman Cunningham", "etype": "poem"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Editorial: Call of the Hills", "author": "Helen Kimball Orgill", "etype": "editorial"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for October", "author": None, "etype": "lesson"},
    ],

    ("Vol10", "No9_September_1923"): [
        # NOTE: This issue's file lacks a formal CONTENTS listing.
        # Entries reconstructed from article headers in the text.
        {"title": "Cumorah", "author": "Ruth May Fox", "etype": "poem"},
        {"title": "The Book of Mormon Tested", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "The Book of Mormon as a Best Seller", "author": None, "etype": "article"},
        {"title": "The Book of Mormon as a Literary Product", "author": None, "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for November", "author": None, "etype": "lesson"},
        {"title": "Teachers' Topic", "author": None, "etype": "lesson"},
    ],

    ("Vol10", "No10_October_1923"): [
        {"title": "The Temple at Cardston, Canada", "author": None, "etype": "article"},
        {"title": "A Temple in Canada", "author": "Helen Orgill", "etype": "poem"},
        {"title": "The Canada Temple", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "President Heber J. Grant", "author": None, "etype": "article"},
        {"title": "President Grant's Dedicatory Prayer", "author": None, "etype": "article"},
        {"title": "Now is the Time", "author": "Annie G. Lauritzen", "etype": "poem"},
        {"title": "Ada Louise Comstock", "author": None, "etype": "article"},
        {"title": "Mother as a Teacher of Religion", "author": "John Quayle", "etype": "article"},
        {"title": "Editorials", "author": None, "etype": "editorial"},
        {"title": "The Great Teacher", "author": "Alfred Osmond", "etype": "poem"},
        {"title": "Mrs. Harriet Perry Whiting", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "Educational Items", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "The Way of Parents", "author": "Strickland Gillilan", "etype": "article"},
    ],

    ("Vol10", "No11_November_1923"): [
        {"title": "Harvest Home", "author": None, "etype": "article"},
        {"title": "Harvest Home", "author": "Alfred Osmond", "etype": "poem"},
        {"title": "Names", "author": None, "etype": "poem"},
        {"title": "Louis Pasteur", "author": None, "etype": "article"},
        {"title": "Pasteur's Contribution to the Relief of Human Suffering", "author": "Dr. F. S. Harris", "etype": "article"},
        {"title": "Faith", "author": None, "etype": "poem"},
        {"title": "Moonlight on the Lake", "author": "Ida R. Alldredge", "etype": "poem"},
        {"title": "Ruth's Thanksgiving", "author": "Elsie Talmage Brandley", "etype": "fiction"},
        {"title": "Nurse Aids' Class", "author": None, "etype": "article"},
        {"title": "Old Man Clegg", "author": None, "etype": "fiction"},
        {"title": "The Reasons for the Christmas Seal", "author": None, "etype": "article"},
        {"title": "Jealousy", "author": "H. L. Johnston", "etype": "article"},
        {"title": "Something to Think About", "author": "Heber J. Sears, M. D.", "etype": "article"},
        {"title": "Ten Reasons Why I Should Subscribe for the Relief Society Magazine", "author": None, "etype": "article"},
        {"title": "One Hundred Years of Teacher Training", "author": "A. E. Winship", "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for January", "author": None, "etype": "lesson"},
        {"title": "Teachers' Topic for January", "author": None, "etype": "lesson"},
    ],

    ("Vol10", "No12_December_1923"): [
        {"title": "Mother and Son in Role of Madonna and Child", "author": None, "etype": "article"},
        {"title": "My Impressions at the Sacred Grove and Hill Cumorah", "author": "Joseph Fielding Smith", "etype": "article"},
        {"title": "Editorials", "author": None, "etype": "editorial"},
        {"title": "Joseph Smith", "author": None, "etype": "article"},
        {"title": "And Then Came Santa", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "Homing Hearts", "author": "Helen Field Fischer", "etype": "poem"},
        {"title": "Relief Society Conference Minutes", "author": "Mrs. Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for February", "author": None, "etype": "lesson"},
        {"title": "Thy Gift", "author": "Alberta Huish", "etype": "poem"},
    ],
}


# ===================================================================
# VOLUME 11 (1924)
# ===================================================================

VOL11_TOC = {
    ("Vol11", "No1_January_1924"): [
        {"title": "The Dreamer", "author": None, "etype": "article"},
        {"title": "Child", "author": "Mrs. Claire Stewart Boyer", "etype": "poem"},
        {"title": "Mrs. Jeannette A. Hyde", "author": None, "etype": "article"},
        {"title": "The Eliza Roxey Snow Memorial Contest", "author": None, "etype": "article"},
        {"title": "New Year's Editorial", "author": None, "etype": "editorial"},
        {"title": "Martha Ann Smith Harris", "author": "Richard P. Harris", "etype": "article"},
        {"title": "National Council of Women", "author": None, "etype": "article"},
        {"title": "Miss Zalia", "author": "Elsie C. Carroll", "etype": "fiction"},
        {"title": "Recommendations of General Board Respecting Maternity and Health", "author": None, "etype": "article"},
        {"title": "Contagious and Infectious Diseases and Quarantine Regulations", "author": "Dr. Jane W. Skolfield", "etype": "article"},
        {"title": "The Companionship of Parents and Children", "author": "Julia A. F. Lund", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for March", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No2_February_1924"): [
        {"title": "Abraham Lincoln", "author": "Ivy Houtz Woolley", "etype": "poem"},
        {"title": "Packing Clothes at the General Office for Central Europe", "author": None, "etype": "article"},
        {"title": "The Joyful Truth", "author": "Annie D. Palmer", "etype": "poem"},
        {"title": "Boxes of Clothes, Utah Stake, Ready to Ship", "author": None, "etype": "article"},
        {"title": "Eliza R. Snow", "author": "Minnie Iverson Hodapp", "etype": "poem"},
        {"title": "As Shadows Pass", "author": "Annie Wells Cannon", "etype": "fiction"},
        {"title": "Lincoln's Widow Writes of Poverty", "author": None, "etype": "article"},
        {"title": "Editorials—Abraham Lincoln Relief Society Clothing Drive for Central Europe", "author": None, "etype": "editorial"},
        {"title": "Bobbie Miller, Flapper", "author": "S. L. Cheney", "etype": "fiction"},
        {"title": "Cleaning Household Silver", "author": "Ethel Cutler Butt", "etype": "article"},
        {"title": "Eight Women Elected to British Parliament", "author": None, "etype": "article"},
        {"title": "Items About Women", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "The Gospel to the Lamanites", "author": "Lucy Wright Snow", "etype": "article"},
        {"title": "Guide Lessons for April", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No3_March_1924"): [
        {"title": "Eliza R. Snow", "author": "Minnie Iverson Hodapp", "etype": "poem"},
        {"title": "Relief Society Day", "author": None, "etype": "article"},
        {"title": "The Resurrection", "author": "Lucy Wright Snow", "etype": "poem"},
        {"title": "Dr. C. H. Levermore", "author": None, "etype": "article"},
        {"title": "The Lord is my Shepherd", "author": "Hattie Critchlow Jensen", "etype": "poem"},
        {"title": "Champions of Woman Suffrage", "author": None, "etype": "article"},
        {"title": "The Relief Society, the First Woman's Organization", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "The B. Y. U. Leadership Nursery", "author": "Laura Gardner", "etype": "article"},
        {"title": "Editorial—The Relief Society Birthday", "author": None, "etype": "editorial"},
        {"title": "Mrs. Woodrow Wilson", "author": None, "etype": "article"},
        {"title": "A Christian Revival in America", "author": "Harrison R. Merrill", "etype": "article"},
        {"title": "A Daughter of the Southern Seas", "author": "Annie D. Palmer", "etype": "fiction"},
        {"title": "Stories Show Human Side of Woodrow Wilson", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for May", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No4_April_1924"): [
        {"title": "An April Sunset", "author": None, "etype": "article"},
        {"title": "I Know How the Mother of Lazarus Felt", "author": "Annie Pike Greenwood", "etype": "poem"},
        {"title": "Orson F. Whitney", "author": None, "etype": "article"},
        {"title": "Editorial—Phoebe Nourse Donated the first Money for a National Cathedral in Washington", "author": None, "etype": "editorial"},
        {"title": "Six Generations in the Church", "author": None, "etype": "article"},
        {"title": "Two Surveys", "author": None, "etype": "article"},
        {"title": "A Perfect Day", "author": None, "etype": "poem"},
        {"title": "Simple Trimming for Summer Dresses", "author": "Violet Elliott", "etype": "article"},
        {"title": "Wisdom of the Ancients Reflected in our Modern Salads", "author": "Elizabeth Cannon", "etype": "article"},
        {"title": "The Scent of the Hyacinth", "author": "Elizabeth Cannon Porter", "etype": "fiction"},
        {"title": "Dr. McCollum Coming to Utah", "author": "Carrie Castle Dogier", "etype": "article"},
        {"title": "Something to Think About", "author": "Heber J. Sears M. D.", "etype": "article"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for June", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No5_May_1924"): [
        {"title": "Brigham Young University Summer School", "author": None, "etype": "article"},
        {"title": "The Essence of a Tear", "author": "Dr. George W. Middleton", "etype": "article"},
        {"title": "How My Mother Got Her Soft Face", "author": "J. M. Barrie", "etype": "article"},
        {"title": "Portrait of Mother of James Matthew Barrie", "author": None, "etype": "article"},
        {"title": "Editorial—Mothers", "author": None, "etype": "editorial"},
        {"title": "The Bereft at Castle Gate", "author": None, "etype": "article"},
        {"title": "\"A Mother Was Born\"", "author": None, "etype": "article"},
        {"title": "Efficient Motherhood", "author": "Claire Stewart Boyer", "etype": "article"},
        {"title": "Getting Ready for Cousin Alice", "author": "Annie Pike Greenwood", "etype": "fiction"},
        {"title": "A Half Century of Educational Progress", "author": None, "etype": "article"},
        {"title": "Something to Think About", "author": "Dr. Heber J. Grant", "etype": "article"},
        {"title": "The Psalmist David, a Modern Singer", "author": "H. R. Merrill", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Relief Society Annual Report", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Teachers' Topic for July", "author": None, "etype": "lesson"},
        {"title": "Mothers' Day", "author": "Florence Pyne Billings", "etype": "poem"},
    ],

    ("Vol11", "No6_June_1924"): [
        {"title": "Executive Committee of Relief Society", "author": None, "etype": "article"},
        {"title": "Relief Society Conference Minutes", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Vital Statistics and Maternity Welfare", "author": None, "etype": "article"},
        {"title": "Object and Preview Lessons", "author": None, "etype": "lesson"},
        {"title": "Theology", "author": "Lotta P. Baxter", "etype": "lesson"},
        {"title": "Literature", "author": None, "etype": "lesson"},
        {"title": "Social Service", "author": "Cora L. Bennion", "etype": "lesson"},
        {"title": "How to Analyze and Prepare Lessons", "author": None, "etype": "lesson"},
        {"title": "Theology", "author": "Julia A. Child", "etype": "lesson"},
        {"title": "Literature", "author": "Annie Wells Cannon", "etype": "lesson"},
        {"title": "Social Service", "author": "Amy W. Evans", "etype": "lesson"},
        {"title": "Teachers' Topic", "author": "Sarah M. McLelland", "etype": "lesson"},
        {"title": "Nurses Aid Class", "author": "Emma A. Empey", "etype": "article"},
        {"title": "Reports from Missions", "author": None, "etype": "report"},
        {"title": "Southern States", "author": "Grace E. Callis", "etype": "report"},
        {"title": "Northern States", "author": "Rachel Grant Taylor", "etype": "report"},
        {"title": "North-Western States", "author": "Marie Young", "etype": "report"},
        {"title": "Addresses", "author": None, "etype": "article"},
        {"title": "Prest. Clarissa S. Williams", "author": None, "etype": "article"},
        {"title": "Prest. Heber J. Grant", "author": None, "etype": "article"},
        {"title": "Teachers' Topic for August", "author": None, "etype": "lesson"},
        {"title": "Editorial—President Williams' Birthday", "author": None, "etype": "editorial"},
    ],

    ("Vol11", "No7_July_1924"): [
        {"title": "Unveiling of President Williams' Portrait", "author": None, "etype": "article"},
        {"title": "Unveiling of President Williams' Portrait", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "What the Pioneers Ate", "author": "Jean Cox", "etype": "article"},
        {"title": "Rosalia Cox Driggs", "author": None, "etype": "article"},
        {"title": "Editorials—A Pioneer's Contribution to a Johns Hopkins Specialist", "author": None, "etype": "editorial"},
        {"title": "The Pioneers Builded Better than they Knew", "author": None, "etype": "editorial"},
        {"title": "The Eighteenth Amendment", "author": "Judge Florence Allen", "etype": "article"},
        {"title": "Goitre", "author": "Dr. J. Wallace", "etype": "article"},
        {"title": "Care of the Expectant Mother", "author": "A Charlotte Dancey", "etype": "article"},
        {"title": "National and International Councils of Women", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Relief Society Nurses", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for September", "author": None, "etype": "lesson"},
        {"title": "Teachers' Topic for September", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No8_August_1924"): [
        {"title": "Green River", "author": None, "etype": "article"},
        {"title": "Her Things", "author": "Claire Stewart Boyer", "etype": "poem"},
        {"title": "Olivia Pratt Driggs", "author": None, "etype": "article"},
        {"title": "Hard Up", "author": None, "etype": "fiction"},
        {"title": "Eliza Roxey Snow Prize Memorial Poem", "author": None, "etype": "article"},
        {"title": "Editorial—Twentieth Century Heresy", "author": None, "etype": "editorial"},
        {"title": "Religion in Russia", "author": None, "etype": "editorial"},
        {"title": "Utah, a Mecca of Education", "author": None, "etype": "editorial"},
        {"title": "The Stricken Family at the White House", "author": None, "etype": "editorial"},
        {"title": "John Bennett's Divorce", "author": "Ivy Williams Stone", "etype": "fiction"},
        {"title": "Not Understood", "author": "Thomas Bracken", "etype": "poem"},
        {"title": "Conference on Prevention of Causes of War", "author": None, "etype": "article"},
        {"title": "The Henry Car", "author": None, "etype": "article"},
        {"title": "Isabel Wardell Wright", "author": None, "etype": "article"},
        {"title": "When the Alien Needs a Friend", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for October", "author": None, "etype": "lesson"},
        {"title": "Teachers' Topic for October", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No9_September_1924"): [
        {"title": "The Scent of the Hyacinth", "author": "Annie Pike Greenwood", "etype": "fiction"},
        {"title": "The Mountains Shall be Laid Low", "author": "Thomas L. Martin", "etype": "article"},
        {"title": "Editorial—Another Centenary—September 1824-1924", "author": None, "etype": "editorial"},
        {"title": "Elizabeth Claridge McCune", "author": None, "etype": "article"},
        {"title": "Cache Valley", "author": None, "etype": "article"},
        {"title": "School Lunches", "author": "Ethel Melville", "etype": "article"},
        {"title": "Etiquette", "author": None, "etype": "article"},
        {"title": "The New Dentist", "author": "Pearl Nelson", "etype": "fiction"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Cheerfulness", "author": "Coral J. Black", "etype": "poem"},
        {"title": "Guide Lessons for November—Theology and Testimony", "author": None, "etype": "lesson"},
        {"title": "Literature", "author": None, "etype": "lesson"},
        {"title": "Social Service", "author": None, "etype": "lesson"},
        {"title": "Teachers' Topic for November", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No10_October_1924"): [
        {"title": "Elizabeth Claridge McCune", "author": None, "etype": "article"},
        {"title": "Elizabeth Claridge McCune", "author": "Augusta W. Grant", "etype": "article"},
        {"title": "A Happy Remembrance", "author": "Lula G. Richards", "etype": "article"},
        {"title": "Why There Should be More Influence of Women in our Legislature", "author": "Dr. Hugh Woodward", "etype": "article"},
        {"title": "Editorial—Woman's Sphere Broadens", "author": None, "etype": "editorial"},
        {"title": "The Associate Editor's Furlough", "author": None, "etype": "editorial"},
        {"title": "Law Enforcement in America", "author": None, "etype": "editorial"},
        {"title": "National Conference of Social Workers", "author": None, "etype": "editorial"},
        {"title": "Portrait of Mrs. Mabel Walker Willebrandt", "author": None, "etype": "article"},
        {"title": "Mrs. Mabel Walker Willebrandt", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "Law and Order in Business", "author": "Mrs. Mabel Walker Willebrandt", "etype": "article"},
        {"title": "The American Prison Association Congress", "author": "Katherine Palm", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "The Widow's Girls", "author": "Elizabeth Cannon Porter", "etype": "fiction"},
        {"title": "Clara A. Fagergren", "author": None, "etype": "article"},
        {"title": "Guide Lessons for December", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No11_November_1924"): [
        {"title": "Boating on the Jordan, in Utah", "author": None, "etype": "article"},
        {"title": "The Fruits of Faith", "author": "Alfred Osmond", "etype": "poem"},
        {"title": "Blessings in Disguise", "author": "Orson F. Whitney", "etype": "article"},
        {"title": "Thanksgiving Day", "author": "Samantha T. B. Foley", "etype": "poem"},
        {"title": "Investing in Love", "author": "Annie D. Palmer", "etype": "fiction"},
        {"title": "The Use of Mental Tests", "author": "Lofter Bjarnason", "etype": "article"},
        {"title": "Editorial—Woman and the Scientific Age", "author": None, "etype": "editorial"},
        {"title": "Conference of Utah Public Health Assn.", "author": None, "etype": "editorial"},
        {"title": "An Appreciation", "author": "Edith Ivins Lamoreaux", "etype": "article"},
        {"title": "A Thanksgiving Lesson", "author": "A. E. Winship", "etype": "article"},
        {"title": "Response", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "Tuberculosis: A Social Disease", "author": None, "etype": "article"},
        {"title": "Out Door Sleeping", "author": "Daline A. Buffington", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Nature's Alchemy", "author": "Linda J. Fletcher", "etype": "poem"},
        {"title": "Guide Lessons for January", "author": None, "etype": "lesson"},
    ],

    ("Vol11", "No12_December_1924"): [
        {"title": "Madonna And Child", "author": None, "etype": "article"},
        {"title": "To Our Beloved Sisters", "author": "Relief Society Presidency", "etype": "article"},
        {"title": "Gold, Frankincense and Myrrh", "author": "Hazel S. Washburn", "etype": "poem"},
        {"title": "At the Relief Society Conference at Honolulu", "author": None, "etype": "article"},
        {"title": "A Trip to Hawaii", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "The Discontinued Custom", "author": "Annie Pike Greenwood", "etype": "fiction"},
        {"title": "Sensible Christmas Giving", "author": "Ramona Wilcox Cannon", "etype": "article"},
        {"title": "Editorial—A Greeting From Across the Sea", "author": None, "etype": "editorial"},
        {"title": "Utah Women Honored by National Council Of Women", "author": None, "etype": "editorial"},
        {"title": "Joseph Smith's Views of Women", "author": None, "etype": "editorial"},
        {"title": "Relief Society Conference Minutes", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for February", "author": None, "etype": "lesson"},
    ],
}


# ===================================================================
# VOLUME 12 (1925)
# ===================================================================

VOL12_TOC = {
    ("Vol12", "No1_January_1925"): [
        {"title": "The Year Has Gone", "author": "Eliza R. Snow", "etype": "poem"},
        {"title": "Portrait of Mrs. Annie D. Palmer", "author": None, "etype": "article"},
        {"title": "Oh, White-Winged Gull", "author": "Mrs. Annie D. Palmer", "etype": "poem"},
        {"title": "Portrait of Mrs. Alice Morrill", "author": None, "etype": "article"},
        {"title": "The Pioneer Mother", "author": "Mrs. Alice Morrill", "etype": "poem"},
        {"title": "Vigilant Loyalty to our Standards of Government", "author": "Elder George Albert Smith", "etype": "article"},
        {"title": "Spiritual Education", "author": "Dr. Adam S. Bennion", "etype": "article"},
        {"title": "Editorial—The Gospel as a Guide", "author": None, "etype": "editorial"},
        {"title": "Mother's Milk Clinic", "author": None, "etype": "article"},
        {"title": "The Editor Abroad", "author": None, "etype": "article"},
        {"title": "A Perfect Ending of an Imperfect Year", "author": "Eunice Iverson Gardner", "etype": "fiction"},
        {"title": "Importance of Diet for the Expectant Mother", "author": None, "etype": "article"},
        {"title": "Women in the Utah Legislature", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for March", "author": None, "etype": "lesson"},
    ],

    ("Vol12", "No2_February_1925"): [
        {"title": "American Fork Canyon in February", "author": None, "etype": "article"},
        {"title": "Love's Romance", "author": "Alfred Lambourne", "etype": "poem"},
        {"title": "The Editor Abroad", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "Eliza S. Neslin", "author": "Lula Greene Richards", "etype": "article"},
        {"title": "Jewels", "author": "Annie Wells Cannon", "etype": "poem"},
        {"title": "A Family of Slaves that Help You", "author": "Newman I. Butt", "etype": "article"},
        {"title": "Like Crumbled Rose Petals", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "Albert Edward Winship", "author": "Alfred Osmond", "etype": "poem"},
        {"title": "Editorial—Dr. Albert Edward Winship", "author": None, "etype": "editorial"},
        {"title": "Lincoln's Appeal for Loyalty to All Laws", "author": None, "etype": "article"},
        {"title": "Diet for the Nursing Mother", "author": "Jean Cox", "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
    ],

    ("Vol12", "No3_March_1925"): [
        {"title": "Poverty", "author": "Ivy Houtz Woolley", "etype": "poem"},
        {"title": "Portrait by Romney", "author": None, "etype": "article"},
        {"title": "Where is Heaven?", "author": "Ruth May Fox", "etype": "poem"},
        {"title": "A Question", "author": "Mrs. Parley Nelson", "etype": "poem"},
        {"title": "Our President", "author": "Laura J. Adamson", "etype": "article"},
        {"title": "National Woman's Relief Society", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Editorial—The Seventeenth of March A Memorable Day for Women", "author": None, "etype": "editorial"},
        {"title": "The Justice Bell", "author": None, "etype": "article"},
        {"title": "The Difference", "author": "Estella Webb Thomas", "etype": "poem"},
        {"title": "A Dear Old Soul", "author": "Sarah B. Moody", "etype": "fiction"},
        {"title": "A Tribute to Our Old Sisterhood", "author": "Bertha A. Kleinman", "etype": "article"},
        {"title": "The Land of Scott and Burns", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "Reference Books on Parliamentary Practice", "author": None, "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Infant Feeding", "author": None, "etype": "article"},
        {"title": "Notes from the Fields", "author": None, "etype": "report"},
        {"title": "Guide Lessons for May", "author": None, "etype": "lesson"},
    ],

    ("Vol12", "No4_April_1925"): [
        {"title": "Entrance to Tomb of the Kings", "author": None, "etype": "article"},
        {"title": "L.D.S.", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "An Easter Thought", "author": "John Henry Evans", "etype": "article"},
        {"title": "Oliver Belnap Jenson", "author": None, "etype": "article"},
        {"title": "Peacock Feathers", "author": "H. L. Johnston", "etype": "fiction"},
        {"title": "The Editor Abroad", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "Child Feeding", "author": "Jean Cox", "etype": "article"},
        {"title": "Gifts", "author": "Lucy Wright Snow", "etype": "poem"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Planning in the Home", "author": "Hattie P. McGavin", "etype": "article"},
        {"title": "\"Peace, be Still\"", "author": "Carrie Tanner", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Influence", "author": "Henry Van Dyke", "etype": "poem"},
        {"title": "Guide Lessons for June", "author": None, "etype": "lesson"},
    ],

    ("Vol12", "No5_May_1925"): [
        {"title": "Mother's Love", "author": "Alfred Osmond", "etype": "poem"},
        {"title": "National Council of Women Quinquennial Campaign", "author": None, "etype": "article"},
        {"title": "The Mother", "author": None, "etype": "article"},
        {"title": "Mrs. Jeanette Acord Hyde", "author": "Dr. George W. Middleton", "etype": "article"},
        {"title": "Resting Time for Mother", "author": "Mary H. Woolsey", "etype": "fiction"},
        {"title": "Editorial—Seeing What the Missionary Predicted Concerning Palestine", "author": None, "etype": "editorial"},
        {"title": "The Missionary Home", "author": None, "etype": "editorial"},
        {"title": "Kate Waller Barrett", "author": "Annie Wells Cannon", "etype": "article"},
        {"title": "To Mother Dear on Mother's Day", "author": "Willard Greene Richards", "etype": "poem"},
        {"title": "Mother's Answer", "author": "Lula Greene Richards", "etype": "poem"},
        {"title": "The Editor Abroad", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "New Board Members", "author": None, "etype": "article"},
        {"title": "Psychology of Child Feeding", "author": "Jean Cox", "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "One Phase of Motherhood", "author": "Susan T. Jennings", "etype": "article"},
        {"title": "May", "author": "Mrs. Alice Foutz", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "My Little Babe", "author": "Fern J. B. Russon", "etype": "poem"},
        {"title": "Teachers' Topic for July", "author": None, "etype": "lesson"},
    ],

    ("Vol12", "No6_June_1925"): [
        {"title": "At the Dawning", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Portrait of President Charles W. Penrose", "author": None, "etype": "article"},
        {"title": "Our Beloved Leader", "author": None, "etype": "article"},
        {"title": "The Assembly Hall, Salt Lake City", "author": None, "etype": "article"},
        {"title": "Relief Society Conference Minutes", "author": None, "etype": "report"},
        {"title": "Greetings and Report", "author": "Clarissa Smith Williams", "etype": "report"},
        {"title": "Preparation for Group Conventions", "author": "Amy W. Evans", "etype": "report"},
        {"title": "Efficient Stake Supervision", "author": "Lotta Paul Baxter", "etype": "report"},
        {"title": "Reports of Stakes on Maternity and Health Work", "author": None, "etype": "report"},
        {"title": "Disaster Relief", "author": "Annie D. Palmer", "etype": "article"},
        {"title": "Supervision in Employment", "author": "Lydia Alder", "etype": "article"},
        {"title": "The Transportation Problem", "author": "Cora Kassius", "etype": "article"},
        {"title": "Family Ties", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Teachers' Topic for August", "author": None, "etype": "lesson"},
        {"title": "Editorial—A Fitting Tribute", "author": None, "etype": "editorial"},
        {"title": "The Contribution of the Emigrant", "author": None, "etype": "editorial"},
        {"title": "Resting Time for Mother", "author": "Mary H. Woolsey", "etype": "fiction"},
    ],

    ("Vol12", "No7_July_1925"): [
        {"title": "The Longest", "author": "Alfred Osmond", "etype": "poem"},
        {"title": "Lula Greene Richards", "author": None, "etype": "article"},
        {"title": "Pioneer Woman Editor", "author": None, "etype": "article"},
        {"title": "Social Service", "author": "Cora Kasius", "etype": "article"},
        {"title": "She Refused to Ride", "author": "Annie Pike Greenwood", "etype": "fiction"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Adelia B. Cox Sidwell", "author": "R. C. Cox", "etype": "article"},
        {"title": "Old Glory", "author": "Hazel S. Washburn", "etype": "poem"},
        {"title": "Nutrition and Health", "author": "Jean Cox", "etype": "article"},
        {"title": "Family Budgets", "author": "Rena B. Maycock", "etype": "article"},
        {"title": "Editor Abroad", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "Sabbath", "author": "E. Curtis", "etype": "poem"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Poetry", "author": None, "etype": "poem"},
        {"title": "Notes from Field", "author": "Amy B. Lyman", "etype": "report"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
        {"title": "Literature", "author": None, "etype": "lesson"},
    ],

    ("Vol12", "No8_August_1925"): [
        {"title": "The White House at Washington D. C.", "author": None, "etype": "article"},
        {"title": "To a Woodpath", "author": "Estelle Webb Thomas", "etype": "poem"},
        {"title": "International Council of Women", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "Mother's Evening Prayer", "author": "Nettie E. McMurtrey", "etype": "poem"},
        {"title": "Tell Your Troubles to the Iceman", "author": "Kate Thomas", "etype": "fiction"},
        {"title": "Editorial—Home and Parenthood Recreation", "author": None, "etype": "editorial"},
        {"title": "The Editor Abroad", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "Vitamins", "author": "Jean Cox", "etype": "article"},
        {"title": "Out of Work", "author": "Martha Hartford Webb", "etype": "fiction"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Susan Taylor Jennings", "author": None, "etype": "article"},
        {"title": "Guide Lessons for October", "author": None, "etype": "lesson"},
    ],

    ("Vol12", "No9_September_1925"): [
        {"title": "The Farmer's Wife Writes a Poem", "author": "Annie Pike Greenwood", "etype": "poem"},
        {"title": "Lake Phoebe (Big Cottonwood Canyon)", "author": "Alfred Lambourne", "etype": "article"},
        {"title": "The Bible and Emily Post", "author": "Agnes Bostonne", "etype": "article"},
        {"title": "Be Patient Little Flock", "author": "Theodore E. Curtis", "etype": "poem"},
        {"title": "A Tribute to John J. McClellan", "author": "Dr. George W. Middleton", "etype": "article"},
        {"title": "Obscurity", "author": "Bertha A. Kleinman", "etype": "poem"},
        {"title": "Editorial—The Bible", "author": None, "etype": "editorial"},
        {"title": "William Jennings Bryan", "author": None, "etype": "editorial"},
        {"title": "The National Conference of Social Work", "author": None, "etype": "editorial"},
        {"title": "Baby Wear", "author": "Vilate Elliot", "etype": "article"},
        {"title": "Molly Crossman Breaks a Tradition of Byfield", "author": "Elsie C. Carroll", "etype": "fiction"},
        {"title": "Beatitudes", "author": "Lula Greene Richards", "etype": "poem"},
        {"title": "The Editor Abroad", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "Humility", "author": "Elsie E. Barrett", "etype": "poem"},
        {"title": "Calories for Safety", "author": "Jean Cox", "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "A Ripe Peach", "author": "Ivy Houtz Woolley", "etype": "poem"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for November", "author": None, "etype": "lesson"},
    ],

    ("Vol12", "No10_October_1925"): [
        {"title": "Autumn", "author": "Annie Wells Cannon", "etype": "poem"},
        {"title": "The Editor Abroad", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "Self-Love", "author": "Elsie E. Barrett", "etype": "poem"},
        {"title": "The Status of Women in Japan", "author": "I. A. Ray Olpin", "etype": "article"},
        {"title": "The Other Side", "author": "Alice Morrill", "etype": "fiction"},
        {"title": "Editorial—Women of the East and the Veil", "author": None, "etype": "editorial"},
        {"title": "American Literature Coming to its Own", "author": None, "etype": "editorial"},
        {"title": "Condolence", "author": None, "etype": "article"},
        {"title": "The Dawn", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Phyllis Morton's Birthday Gift", "author": "Myrtle M. Dean", "etype": "fiction"},
        {"title": "Diet for the Woman of Forty Plus", "author": "Jean Cox", "etype": "article"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Utah State Conference of Social Workers", "author": None, "etype": "article"},
        {"title": "Our Heritage", "author": "Josephine Spencer", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for December", "author": None, "etype": "lesson"},
        {"title": "Love Patriotism", "author": "Susan Coolidge", "etype": "poem"},
    ],

    ("Vol12", "No11_November_1925"): [
        {"title": "Rheims Cathedral", "author": None, "etype": "article"},
        {"title": "Armistice Hymn", "author": None, "etype": "poem"},
        {"title": "Diet for the School Child", "author": "Jean Cox", "etype": "article"},
        {"title": "The Editor Abroad", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "Editorial—Arise and Shine Amid the World's Deep Night", "author": None, "etype": "editorial"},
        {"title": "Armistice Day", "author": None, "etype": "editorial"},
        {"title": "Home Again", "author": None, "etype": "editorial"},
        {"title": "Condolence", "author": None, "etype": "article"},
        {"title": "My Prayer", "author": "Juanita Pulsipher", "etype": "poem"},
        {"title": "Golden-Rod", "author": "Elsie Talmage Brandley", "etype": "fiction"},
        {"title": "Endurance", "author": "Josie E. Childs", "etype": "poem"},
        {"title": "Of Interest to Women", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "Your Flag and My Flag", "author": "Nesbit", "etype": "poem"},
        {"title": "Keep a Health Budget", "author": "James H. Wallis", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "Guide Lessons for January, 1926", "author": None, "etype": "lesson"},
    ],

    ("Vol12", "No12_December_1925"): [
        {"title": "The Christ, by Thorwaldsen", "author": None, "etype": "article"},
        {"title": "Come, Thou Glorious Day of Promise", "author": "A. Alex. Neibaur", "etype": "poem"},
        {"title": "The Editor Abroad", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "\"If Ye Have Faith\"", "author": "Claire Stewart Boyer", "etype": "poem"},
        {"title": "Relief Society Conference", "author": "Amy Brown Lyman", "etype": "report"},
        {"title": "State Welfare Workers Meet", "author": "Julia A. F. Lund", "etype": "article"},
        {"title": "Editorial—Yuletide in Jerusalem", "author": None, "etype": "editorial"},
        {"title": "The Rock of Our Salvation", "author": None, "etype": "editorial"},
        {"title": "The Semi-Centennial of the Brigham Young University", "author": None, "etype": "editorial"},
        {"title": "Semi-Centennial Prayer", "author": "Annie Pike Greenwood", "etype": "poem"},
        {"title": "Dr. Valeria Parker", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Condolence", "author": None, "etype": "article"},
        {"title": "The Home", "author": "Alfred Osmond", "etype": "poem"},
        {"title": "Tennyson, The Boy and the Match", "author": "Annie Pike Greenwood", "etype": "article"},
    ],
}
