"""
Table of Contents for Relief Society Magazine Volumes 33-40
Manually extracted from cleaned data files using LLM/NLP understanding

Format: TOC = { ("VolN", "NoX_Month_Year"): [entries], ... }
Each entry: {"title": str, "author": str or None, "etype": str}
"""

TOC = {
    # ===================================================================
    # VOLUME 33 (1946)
    # ===================================================================

    ("Vol33", "No1_January_1946"): [
        {"title": "Frontispiece Picture General Presidency of Relief Society", "author": None, "etype": "front_matter"},
        {"title": "New Year's Greeting", "author": "Belle S. Spafford", "etype": "editorial"},
        {"title": "Margaret Cummock Pickering", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Award Winners Eliza Roxey Snow Memorial Prize Poem Contest", "author": None, "etype": "article"},
        {"title": "Star of Gold", "author": "Eva Willes Wangsgaard", "etype": "poem"},
        {"title": "I Shall Be Late", "author": "Betty Wall Madsen", "etype": "poem"},
        {"title": "The Good Inheritance", "author": "Caroline Eyring Miner", "etype": "poem"},
        {"title": "Award Winners Relief Society Short Story Contest", "author": None, "etype": "article"},
        {"title": "Spring Festival", "author": "Mary Ek Knowles", "etype": "fiction"},
        {"title": "Nicholas G. Smith A Tribute", "author": "Marion G. Romney", "etype": "article"},
        {"title": "Drifting Or Sailing to a Charted Course", "author": "Lella Marler Hoggan", "etype": "article"},
        {"title": "Unceasing Crusade National Foundation For Infantile Paralysis", "author": None, "etype": "article"},
        {"title": "Mormonism In the Eyes of the Press: Dolly Madison and the Outcast Mormons", "author": "James R. Clark", "etype": "article"},
        {"title": "Let Us Fittingly Mark the Land", "author": "Howard R. Driggs", "etype": "article"},
        {"title": "And For Eternity Chapter 8", "author": "Olive Woolley Burt", "etype": "article"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Be Not Weary in Well Doing", "author": "Marianne C. Sharp", "etype": "editorial"},
        {"title": "Howard S. McDonald Inaugurated President of Brigham Young University", "author": None, "etype": "article"},
        {"title": "Blanche B. Stoddard Resigns as General Secretary-Treasurer", "author": None, "etype": "article"},
        {"title": "In Memoriam: Elder Joseph J. Cannon and Elder Burton K. Farnsworth", "author": None, "etype": "article"},
        {"title": "Only One Relief Society Conference to be Held Each Year", "author": None, "etype": "article"},
        {"title": "Only One Relief Society Assigned Evening Meeting Fast Sunday in March", "author": None, "etype": "article"},
        {"title": "Suggestions to Contributors", "author": None, "etype": "article"},
        {"title": "Messages From the Missions", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "The United Order Begun and Its Establishment in the Settlements", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Charity Hopeth All Things, Charity Endureth All Things", "author": "Lowell L. Bennion", "etype": "lesson"},
        {"title": "Some Broader Applications of Social Ethics", "author": "Harold T. Christensen", "etype": "lesson"},
        {"title": "The Infinite Frontispiece", "author": "Grace Sayre", "etype": "poem"},
        {"title": "After A While", "author": "Maude Hatch Benedict", "etype": "poem"},
        {"title": "Elijah", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "The Weight of Your Cloud", "author": "Edna S. Dustin", "etype": "poem"},
        {"title": "Shopping For a Doll", "author": "Hazel Jones Owen", "etype": "poem"},
        {"title": "Promise", "author": "Christie Lund Coles", "etype": "poem"},
        {"title": "I Know a Road", "author": "Violet Harris Hendrickson", "etype": "poem"},
        {"title": "Hill Woman", "author": "Maude Blixt Trone", "etype": "poem"},
        {"title": "The Morning Star", "author": "Courtney E. Cottam", "etype": "poem"},
        {"title": "Letter", "author": "Nan S. Richardson", "etype": "poem"},
    ],

    ("Vol33", "No2_February_1946"): [
        {"title": "American Statesmen Their Attitude Toward God", "author": "El Ray L. Christiansen", "etype": "article"},
        {"title": "Mormonism in the Eyes of the Press: The World Receives the News of Joseph Smith's Death", "author": "James R. Clark", "etype": "article"},
        {"title": "Abraham Lincoln Speaks Again", "author": "Vesta P. Crawford", "etype": "article"},
        {"title": "What the Children Can Do For Dr.", "author": "M. Lynn Bennion", "etype": "article"},
        {"title": "Fifty and One Ideas For You and For Your Home", "author": "Blanche M. Condie", "etype": "article"},
        {"title": "The Ring of Strength", "author": "Alice Morrey Bailey", "etype": "fiction"},
        {"title": "Ring Out the Old", "author": "Estelle Webb Thomas", "etype": "fiction"},
        {"title": "And For Eternity Chapter 9", "author": "Olive Woolley Burt", "etype": "article"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Star in Her Window", "author": "Ruth H. Chadwick", "etype": "article"},
        {"title": "Study My Word", "author": "Marianne C. Sharp", "etype": "editorial"},
        {"title": "Congratulations to Sister Lyman on Her Birthday", "author": None, "etype": "article"},
        {"title": "Messages From the Missions (Continued)", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Music Notes", "author": "Florence J. Madsen", "etype": "article"},
        {"title": "The Building of Temples Continues", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Charity Never Faileth", "author": "Lowell L. Bennion", "etype": "lesson"},
        {"title": "Bible Influence as Revealed in Children's Literature", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "Morality and the Church", "author": "Harold T. Christensen", "etype": "lesson"},
        {"title": "The Dream Is Ours Frontispiece", "author": "Christie Lund Coles", "etype": "poem"},
        {"title": "To Elizabeth", "author": "Olive M. Nicholes", "etype": "poem"},
        {"title": "The Storm", "author": "Evelyn Fjeldsted", "etype": "poem"},
        {"title": "To Marie", "author": "Adeline J. Haws", "etype": "poem"},
        {"title": "My Old Green Chest", "author": "Grace M. Candland", "etype": "poem"},
        {"title": "Elsie C. Carroll", "author": None, "etype": "poem"},
        {"title": "Twilight", "author": "Ada N. Jones", "etype": "poem"},
        {"title": "Crucible", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "A Prayer", "author": "Celia Van Cott", "etype": "poem"},
    ],

    ("Vol33", "No3_March_1946"): [
        {"title": "Relief Society and the Future", "author": "Leah D. Widtsoe", "etype": "article"},
        {"title": "A Few of Our Gifted Utah Women Artists Part III", "author": "Alice Merrill Horne", "etype": "article"},
        {"title": "The First Easter A Fantasy", "author": "Evelyn Wooster Viner", "etype": "article"},
        {"title": "An Open Door to Happiness", "author": "Wilford D. Lee", "etype": "article"},
        {"title": "Our Parks and Playgrounds", "author": "Fred Tedesco", "etype": "article"},
        {"title": "The Clouded Window", "author": "Caroline Eyring Miner", "etype": "article"},
        {"title": "Thrift Begins In The Garden", "author": "Vesta P. Crawford", "etype": "article"},
        {"title": "Lady-in-Waiting", "author": "Marguerite J. Griffin", "etype": "article"},
        {"title": "All Is Known", "author": "Irva Pratt Andrus", "etype": "fiction"},
        {"title": "Prelude to Spring", "author": "Beatrice Rordame Parsons", "etype": "fiction"},
        {"title": "Even the Frail", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "The Best Little Shrub", "author": "Mabel Harmer", "etype": "fiction"},
        {"title": "And For Eternity Chapter 10 (Conclusion)", "author": "Olive Woolley Burt", "etype": "article"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "A Thing of Beauty is a Joy Forever", "author": "Gertrude R. Garff", "etype": "editorial"},
        {"title": "New Serial to Begin in April", "author": None, "etype": "article"},
        {"title": "Messages From the Missions (Continued)", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Save Those Precious Scraps", "author": "Eleanor Welch Schow", "etype": "article"},
        {"title": "Renewal Frontispiece", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "Her Staff", "author": "Hortense Spencer Andersen", "etype": "poem"},
        {"title": "The Difference", "author": "Cleo Gordon", "etype": "poem"},
        {"title": "Easter Lily", "author": "Evelyn Fjeldsted", "etype": "poem"},
        {"title": "Late Motherhood", "author": "Eva Willes Wangsgaard", "etype": "poem"},
        {"title": "Remember Love", "author": "Anna Prince Redd", "etype": "poem"},
        {"title": "Lesson", "author": "Katherine Fernelius Larsen", "etype": "poem"},
        {"title": "Lesson", "author": "Roberta Bates", "etype": "poem"},
        {"title": "She Hangs the Linen on the Line", "author": "Dott J. Sartori", "etype": "poem"},
        {"title": "Call of Spring", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "Springtime in the West", "author": "Lydia Hall", "etype": "poem"},
        {"title": "March Promises", "author": "Aileen M. Overfelt", "etype": "poem"},
        {"title": "New Things", "author": "Watson Anderson", "etype": "poem"},
    ],

    ("Vol33", "No4_April_1946"): [
        {"title": "Concerning Jesus of Nazareth", "author": None, "etype": "article"},
        {"title": "An Aria for Easter", "author": "Vesta P. Crawford", "etype": "article"},
        {"title": "The Infallible Spirit", "author": "Etta Mai Scott", "etype": "article"},
        {"title": "Our Number One Enemy Cancer", "author": "Utah Division American Cancer Society", "etype": "article"},
        {"title": "Opinions on Alcohol", "author": "Selected", "etype": "article"},
        {"title": "Magic Word", "author": "Mary Ek Knowles", "etype": "article"},
        {"title": "Digging For Happiness", "author": "Elizabeth Adamson", "etype": "article"},
        {"title": "Between the Dusk and the Dark", "author": "Alice Whitson Norton", "etype": "article"},
        {"title": "A Floral Symphony", "author": "Betti Williamson", "etype": "article"},
        {"title": "Faith Is a Heritage Chapter I", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "There Is Truth", "author": "Eva Willes Wangsgaard", "etype": "fiction"},
        {"title": "The White Picket Fence", "author": "Sarah O. Moss", "etype": "fiction"},
        {"title": "Emulating Grandmother", "author": "Linda S. Fletcher", "etype": "fiction"},
        {"title": "The Scar", "author": "Martha Robeson Wright", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Patient in Spirit", "author": "Marianne C. Sharp", "etype": "editorial"},
        {"title": "Congratulations to President Smith", "author": None, "etype": "article"},
        {"title": "Relief Society No Longer to Share in Use of the Evenings of the Stake Quarterly Conference Sundays", "author": None, "etype": "article"},
        {"title": "Messages from the Missions (Concluded)", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Let's Make Dickies", "author": "Etta S. Robbins", "etype": "article"},
        {"title": "Before the Dawn", "author": "Olive M. Nicholes", "etype": "poem"},
        {"title": "Echoes of Hope", "author": "Ivy Houtz Woolley", "etype": "poem"},
        {"title": "Springtime Knowledge", "author": "Genevieve Van Wagenen", "etype": "poem"},
        {"title": "Father, Forgive Them", "author": "Dott J. Sartori", "etype": "poem"},
        {"title": "When He Returns", "author": "Ruth H. Chadwick", "etype": "poem"},
        {"title": "Remembering", "author": "Anna Prince Redd", "etype": "poem"},
        {"title": "When the Choir Broadcasts", "author": "Rebecca Merrill Ostler", "etype": "poem"},
        {"title": "Aftermath", "author": "Jo Adelaide Stock", "etype": "poem"},
        {"title": "The Locust Tree", "author": "Katherine Fernelius Larsen", "etype": "poem"},
        {"title": "Voice of Cumorah", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "Offerings", "author": "Marguerite J. Griffin", "etype": "poem"},
        {"title": "Apple Tree in April", "author": "Gene Romolo", "etype": "poem"},
        {"title": "Spring Shadows", "author": "Elsie E. Barrett", "etype": "poem"},
        {"title": "Spring Sonnet", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "God Must Love the Beautiful", "author": "Mabel Jones Gabbott", "etype": "poem"},
    ],

    ("Vol33", "No5_May_1946"): [
        {"title": "Three Miniatures From Life: The Mothers of the First Presidency", "author": "Luacine C. Fox", "etype": "article"},
        {"title": "In Memoriam: President Louise Y. Robison", "author": "Kate M. Barker", "etype": "article"},
        {"title": "Women Poets in Review Part I", "author": "Anna Boss Hart", "etype": "article"},
        {"title": "Are We Protecting Our Children?", "author": "Leone O. Jacobs", "etype": "article"},
        {"title": "The Gift of the Genie", "author": "LaRene King Bleecker", "etype": "article"},
        {"title": "Filleth the Hungry Soul", "author": "Frances C. Yost", "etype": "fiction"},
        {"title": "Faith Is a Heritage Chapter 2", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Return of Spring", "author": "Vesta P. Crawford", "etype": "editorial"},
        {"title": "In Memoriam: Pauline Taggart Pingree", "author": None, "etype": "article"},
        {"title": "The Magazine Honor Roll for 1945", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Notes From the Field", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Comments From Magazine Readers", "author": None, "etype": "article"},
        {"title": "Comments From Magazine Writers", "author": None, "etype": "article"},
        {"title": "Grosgrain Ribbon Handbag", "author": None, "etype": "article"},
        {"title": "To Louise Y. Robison Frontispiece", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "I Heard a Robin Singing", "author": "Zara Sabin", "etype": "poem"},
        {"title": "Mother's Day Greeting", "author": "Robert Layton", "etype": "poem"},
        {"title": "Mother", "author": "Delsa Davis McBride", "etype": "poem"},
        {"title": "The Teacher", "author": "Mary E. Abel", "etype": "poem"},
        {"title": "Sunset Divine", "author": "Pauline Kirkwood", "etype": "poem"},
        {"title": "Mother of Mine", "author": "Vernessa M. Nagle", "etype": "poem"},
        {"title": "Relief Society Magazine May", "author": "Weight Johnson", "etype": "poem"},
        {"title": "Mother's Notebook", "author": "Dott J. Sartori", "etype": "poem"},
        {"title": "Meadow Lark", "author": "Roberta Bates", "etype": "poem"},
    ],

    ("Vol33", "No6_June_1946"): [
        {"title": "Fasting", "author": "Priscilla L. Evans", "etype": "article"},
        {"title": "Isabel Barton Callister Called to General Board", "author": "Lillie C. Adams", "etype": "article"},
        {"title": "Contest Announcements 1946", "author": None, "etype": "article"},
        {"title": "The Settlement of Sanpete Valley Part I", "author": "Leda Thompson Jensen", "etype": "article"},
        {"title": "Women Poets in Review Part II", "author": "Anna Boss Hart", "etype": "article"},
        {"title": "A Compliment for Mom", "author": "Olive W. Burt", "etype": "article"},
        {"title": "The Price", "author": "Marjorie M. Hamrick", "etype": "article"},
        {"title": "Choosing Roses for the Home Garden", "author": "Hazel D. Moyle", "etype": "article"},
        {"title": "The 116th Annual General Conference", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "The Bennetts' Bookkeeping System", "author": "Alice Whitson Norton", "etype": "article"},
        {"title": "Only Human", "author": "Marguerite J. Griffin", "etype": "article"},
        {"title": "The Price", "author": "T. A. Hunt", "etype": "article"},
        {"title": "Faith Is a Heritage Chapter 3", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Enlarge Your Souls", "author": "Marianne C. Sharp", "etype": "editorial"},
        {"title": "In Memoriam: Alice Robinson", "author": None, "etype": "article"},
        {"title": "General Activities and Special Programs", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Mesh-Sack Magic", "author": None, "etype": "article"},
        {"title": "For the Coming Night Frontispiece", "author": "Grace Sayre", "etype": "poem"},
        {"title": "Dott J. Sartori", "author": None, "etype": "poem"},
        {"title": "Jewel Box", "author": "Jessie Miller Robinson", "etype": "poem"},
        {"title": "Sanctuary", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "My Father", "author": "Jennie Pyper Johnson", "etype": "poem"},
        {"title": "Peace in a Garden", "author": "Celia A. Van Cott", "etype": "poem"},
        {"title": "Summer Song", "author": "Margery S. Stewart", "etype": "poem"},
        {"title": "The Origin of Song", "author": "Katherine Fernelius Larsen", "etype": "poem"},
        {"title": "Class Reunion", "author": "Olive M. Nicholes", "etype": "poem"},
        {"title": "Little Quails Take to the Woods", "author": "Lydia Hall", "etype": "poem"},
        {"title": "Mothers of This Day", "author": "Gene Romolo", "etype": "poem"},
    ],

    ("Vol33", "No7_July_1946"): [
        {"title": "Opportunities at Brigham Young University for the Youth of the Church", "author": "Howard S. McDonald", "etype": "article"},
        {"title": "John H. Taylor", "author": "Richard L. Evans", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: Indians on the Plains", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "The Settlement of Sanpete Valley Part II", "author": "Leda Thompson Jensen", "etype": "article"},
        {"title": "Summer Blossoms for the Home", "author": "Vesta P. Crawford", "etype": "article"},
        {"title": "Grain for the Food of Man", "author": "Eva Willes Wangsgaard", "etype": "article"},
        {"title": "Rag Rug Weaving in Emigration Stake", "author": "Lillie C. Adams", "etype": "article"},
        {"title": "Notes on the Authors of the Lessons", "author": "Leone G. Layton", "etype": "article"},
        {"title": "Faith Is a Heritage Chapter 4", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "The Pioneering Heritage", "author": "Marianne C. Sharp", "etype": "editorial"},
        {"title": "Congratulations to Sister Augusta Winters Grant", "author": None, "etype": "article"},
        {"title": "The Course of Study for 1946-1947", "author": None, "etype": "article"},
        {"title": "General Activities and Special Programs (Continued)", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Suggestions and Instructions on the Educational Program 1946-1947", "author": None, "etype": "article"},
        {"title": "The Organized Church Moves Forward", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Love of God", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Choosing the Right Clothes", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "Our American Indians in Literature", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "Man's Pre-Earth Life", "author": "T. Edgar Lyon", "etype": "lesson"},
        {"title": "The Family Unit Eternal", "author": "Social Science Committee", "etype": "lesson"},
        {"title": "Only the Believer Frontispiece", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Abundance", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "Restoration", "author": "Grace D. Terrell", "etype": "poem"},
        {"title": "One Family", "author": "Maude Blixt Trone", "etype": "poem"},
        {"title": "Acres of Wheat", "author": "Gene Romolo", "etype": "poem"},
        {"title": "These Things I Know", "author": "Mabel Jones Gabbott", "etype": "poem"},
        {"title": "Please, God", "author": "Edna S. Dustin", "etype": "poem"},
        {"title": "Desert Beauty", "author": "Ethel VanHook Hopper", "etype": "poem"},
        {"title": "To a Great Leader", "author": "Bertha M. Rosevear", "etype": "poem"},
    ],

    ("Vol33", "No8_August_1946"): [
        {"title": "The Importance of Thrift", "author": "Alma Sonne", "etype": "article"},
        {"title": "Cache Valley Part of the Mormon Epic", "author": "Caroline Eyring Miner", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: The Indians of Utah and the Black Hawk War", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Garden Making for Centennial Days", "author": "Hazel D. Moyle", "etype": "article"},
        {"title": "Photographing Your Children", "author": "Willard Luce", "etype": "article"},
        {"title": "Heavenly Harmony", "author": "Rachel B. Ballantyne", "etype": "article"},
        {"title": "Menus By the Day Or By the Week", "author": "Miranda Snow Walton", "etype": "article"},
        {"title": "Night Callers", "author": "Gladys Dewey", "etype": "fiction"},
        {"title": "Faith Is a Heritage Chapter 5", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Personal Development Through Service", "author": "Gertrude R. Garff", "etype": "editorial"},
        {"title": "May Anderson Friend of the Children", "author": None, "etype": "article"},
        {"title": "Annual Relief Society General Conference", "author": None, "etype": "article"},
        {"title": "General Activities and Special Programs (Continued)", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "The Priesthood Quorums Expanded", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Love of Fellow Man", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "The Use of Tools and Treatment of Materials", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "Colonial Founders of America in Literature", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "The Mayflower Compact", "author": None, "etype": "article"},
        {"title": "The General Gospel Plan", "author": "T. Edgar Lyon", "etype": "lesson"},
        {"title": "The Family Organization", "author": "Social Science Committee", "etype": "lesson"},
        {"title": "And What of Time Frontispiece", "author": "Mabel Jones Gabbott", "etype": "poem"},
        {"title": "Self-Confidence", "author": "Katherine Fernelius Larsen", "etype": "poem"},
        {"title": "Skull Valley", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "Jessie Miller Robinson", "author": None, "etype": "poem"},
        {"title": "The Silent Bard", "author": "Evelyn Fjeldsted", "etype": "poem"},
        {"title": "The New Testament", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Irrigation", "author": "Della Adams Leitner", "etype": "poem"},
        {"title": "Priceless Gem", "author": "Ruth H. Chadwick", "etype": "poem"},
        {"title": "The Poplars", "author": "Thelma Ireland", "etype": "poem"},
        {"title": "Iris", "author": "Schow", "etype": "poem"},
        {"title": "Late Traveler", "author": "G. Gwen Kelsey", "etype": "poem"},
    ],

    ("Vol33", "No9_September_1946"): [
        {"title": "A Message to Teachers", "author": "M. Lynn Bennion", "etype": "article"},
        {"title": "Fort Lemhi Mission, Idaho Pioneer in Review", "author": "Dorothy Clapp Robinson", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: The Indians and the Mail Route", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "There Is Still Life", "author": "Frances C. Yost", "etype": "fiction"},
        {"title": "A Shelter for Their Hearts", "author": "Maryhale Woolsey", "etype": "fiction"},
        {"title": "Faith Is a Heritage Chapter 6", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Records of Service", "author": "Marianne C. Sharp", "etype": "editorial"},
        {"title": "Ward Relief Society Conferences", "author": None, "etype": "article"},
        {"title": "Bound Volumes", "author": None, "etype": "article"},
        {"title": "United States Savings Bonds", "author": "George Albert Smith", "etype": "article"},
        {"title": "Annual Report 1945", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Notes From the Field", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "The Relief Society Developed", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Faith", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Fitting and Adjusting Patterns and Cutting", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "America's First War for Freedom", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "Faith", "author": "T. Edgar Lyon", "etype": "lesson"},
        {"title": "Autumn Hills Frontispiece", "author": "Grace Zenor Pratt", "etype": "poem"},
        {"title": "Three Precious Things", "author": "Mabel Jones Gabbott", "etype": "poem"},
        {"title": "Clarence Edwin Flynn", "author": None, "etype": "poem"},
        {"title": "Fall Days Are Closing", "author": "Grace M. Candland", "etype": "poem"},
        {"title": "Fulfillment", "author": "Verda P. Bollschweiler", "etype": "poem"},
        {"title": "His Silences", "author": "Blanche Kendall McKey", "etype": "poem"},
        {"title": "Song", "author": "Margery S. Stewart", "etype": "poem"},
        {"title": "Autumn Has Spoken", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Heart's Reply", "author": "Anna Prince Redd", "etype": "poem"},
    ],

    ("Vol33", "No10_October_1946"): [
        {"title": "Pioneer Preparations for Winter", "author": "Ann P. Nibley", "etype": "article"},
        {"title": "Three Natural Bridges of Utah", "author": "Willard Luce", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: A Stampede on the Plains", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Painted Weeds from Fairyland", "author": "Rosella F. Larkin", "etype": "article"},
        {"title": "Golden Harvest", "author": "Beatrice Rordame Parsons", "etype": "article"},
        {"title": "The Intruder", "author": "Margery S. Stewart", "etype": "fiction"},
        {"title": "Faith Is a Heritage Chapter 7", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sallie-Start-Something", "author": "Alice Whitson Norton", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "The Importance of Child Training", "author": "Vesta P. Crawford", "etype": "editorial"},
        {"title": "Notes From the Field", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Regulations Governing the Submittal of Material for Notes From the Field", "author": None, "etype": "article"},
        {"title": "The Educational System Developed", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Courage", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Stitches and Seams", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "Youthtime of a Nation Dedicated to Freedom", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "Repentance", "author": "T. Edgar Lyon", "etype": "lesson"},
        {"title": "Social Science Committee", "author": None, "etype": "lesson"},
        {"title": "Yesterdays Frontispiece", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "God Speed the Plow", "author": "Anonymous", "etype": "poem"},
        {"title": "The Meaning of Autumn", "author": "Evelyn Fjeldsted", "etype": "poem"},
        {"title": "Our Goal", "author": "Grace Zenor Pratt", "etype": "poem"},
        {"title": "Nothing Is Lost", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Crocheting", "author": "Merling Dennis Clyde", "etype": "poem"},
        {"title": "Triolet", "author": "Grace M. Candland", "etype": "poem"},
        {"title": "Parade", "author": "Courtney Cottam", "etype": "poem"},
    ],

    ("Vol33", "No11_November_1946"): [
        {"title": "Relief Society Women Received at the White House", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "Inter-Continental Conference of the National Council of Women", "author": "Priscilla L. Evans", "etype": "article"},
        {"title": "A Visit to Church Shrines", "author": "Edith S. Elliott", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: On the River Platte", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "What Shall I Do Now, Mother?", "author": "Elizabeth Williamson", "etype": "article"},
        {"title": "The Luxury of Giving", "author": "Norma Wrathall", "etype": "fiction"},
        {"title": "As You Were", "author": "Martha Robeson Wright", "etype": "fiction"},
        {"title": "Faith Is a Heritage Chapter 8", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "She Looketh Well to the Ways of Her Household", "author": "Marianne C. Sharp", "etype": "editorial"},
        {"title": "Notes From the Field", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "More Auxiliary Organizations of the Church Started", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Industry", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Pinning, Basting, Pressing, Edges and Seam Finishings", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "Westward March of America", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "Baptism", "author": "T. Edgar Lyon", "etype": "lesson"},
        {"title": "Observing a Principle of Prosperity", "author": "Social Science Committee", "etype": "lesson"},
        {"title": "Where Dreams Were Made Frontispiece", "author": "Anna Prince Redd", "etype": "poem"},
        {"title": "Words", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Keys", "author": "Clarence Edwin Flynn", "etype": "poem"},
        {"title": "Night", "author": "Bernice Hacking Balle", "etype": "poem"},
        {"title": "Autumn Wind", "author": "Katherine Fernelius Larsen", "etype": "poem"},
        {"title": "The Jungle Tree", "author": "Elsie F. Parton", "etype": "poem"},
        {"title": "Friendly Town", "author": "Bertha A. Kleinman", "etype": "poem"},
        {"title": "Consolation", "author": "Zara Sabin", "etype": "poem"},
        {"title": "Hill-Top House", "author": "Beatrice K. Ekman", "etype": "poem"},
    ],

    ("Vol33", "No12_December_1946"): [
        {"title": "Our Wives and Our Mothers in the Eternal Plan", "author": "J. Reuben Clark, Jr.", "etype": "article"},
        {"title": "Hearken to Counsel", "author": "Joseph Fielding Smith", "etype": "article"},
        {"title": "The Place of Relief Society in the Welfare Plan", "author": "Harold B. Lee", "etype": "article"},
        {"title": "Bruce Redd McConkie Sustained a Member of the First Council of Seventy", "author": "Marianne C. Sharp", "etype": "article"},
        {"title": "Marvin O. Ashton", "author": "Bryant S. Hinckley", "etype": "article"},
        {"title": "Christmas and the True Christian Spirit", "author": "T. Edgar Lyon", "etype": "article"},
        {"title": "Christmas on the Mantel", "author": "Elizabeth Williamson", "etype": "article"},
        {"title": "Prelude to Christmas", "author": "Frances C. Yost", "etype": "fiction"},
        {"title": "Faith Is a Heritage Chapter 9", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "A Tie That Binds", "author": "Gertrude R. Garff", "etype": "editorial"},
        {"title": "In Memoriam: Grace Elizabeth Pack Callis", "author": None, "etype": "article"},
        {"title": "Organizations and Reorganizations of Mission and Stake Relief Societies", "author": None, "etype": "article"},
        {"title": "The Welfare Plan Initiated", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Self Reliance", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Finishing, Trimming, Collars, Bands, Hems", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "Carrying America Across a Continent", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "Laying On of Hands for the Gift of the Holy Ghost", "author": "T. Edgar Lyon", "etype": "lesson"},
        {"title": "Importance of Religious Instruction in the Home", "author": "Social Science Committee", "etype": "lesson"},
        {"title": "The Traveler Frontispiece", "author": "Margery S. Stewart", "etype": "poem"},
        {"title": "The House of Bread", "author": "Anna Prince Redd", "etype": "poem"},
        {"title": "Christmas-Eve Magic", "author": "Mary J. Morris", "etype": "poem"},
        {"title": "The Grandmother", "author": "Theoda Hart Struthers", "etype": "poem"},
        {"title": "Dressing a Doll", "author": "Jeanette P. Parry", "etype": "poem"},
        {"title": "Precious Seasons", "author": "Maud Blixt Trone", "etype": "poem"},
        {"title": "Not Comfortless", "author": "Thelma Ireland", "etype": "poem"},
        {"title": "Christmas Cards", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "Dorothy J. Roberts", "author": None, "etype": "poem"},
    ],

    # ===================================================================
    # VOLUME 34 (1947)
    # ===================================================================

    ("Vol34", "No1_January_1947"): [
        {"title": "The New Year", "author": "General Presidency of Relief Society", "etype": "article"},
        {"title": "Unveiling of the Portrait of President Belle S. Spafford", "author": "Marianne C. Sharp", "etype": "article"},
        {"title": "A New Latter-day Saint Artist", "author": "Gerrit de Jong, Jr.", "etype": "article"},
        {"title": "Award Winners Eliza Roxey Snow Memorial Prize Poem Contest", "author": None, "etype": "article"},
        {"title": "Our Hands in Thine", "author": "Ethel Newman Eccles", "etype": "poem"},
        {"title": "Release From the South Seas", "author": "Eva Willes Wangsgaard", "etype": "poem"},
        {"title": "Centennial Conversation", "author": "Miranda Snow Walton", "etype": "poem"},
        {"title": "Award Winners Annual Relief Society Short Story Contest", "author": None, "etype": "article"},
        {"title": "The Return", "author": "Margery S. Stewart", "etype": "fiction"},
        {"title": "Mary Jacobs Wilson Called to General Board", "author": "Maurine C. Neilsen", "etype": "article"},
        {"title": "Florence Gay Smith", "author": "Blanche B. Stoddard", "etype": "article"},
        {"title": "Lillie Chipman Adams", "author": "Isabel B. Callister", "etype": "article"},
        {"title": "General Relief Society Conference", "author": None, "etype": "article"},
        {"title": "The Final Year in the Church History Course", "author": "H. Wayne Driggs", "etype": "article"},
        {"title": "The Worth of Testimony Bearing", "author": "Achsa E. Paxman", "etype": "article"},
        {"title": "Our Pioneer Heritage", "author": "Ann P. Nibley", "etype": "article"},
        {"title": "The Sewing Course", "author": "Velma N. Simonsen", "etype": "article"},
        {"title": "The Gospel as a Way of Life", "author": "Priscilla L. Evans", "etype": "article"},
        {"title": "Congregational Singing and Song Practice", "author": "Blanche B. Stoddard", "etype": "article"},
        {"title": "The Importance of Music in Relief Society", "author": "Florence J. Madsen", "etype": "article"},
        {"title": "Report and Official Instructions", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "Tribute to Sister Louise Y. Robison", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "Faith Is a Heritage Chapter 10", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "The New Frontier", "author": "Vesta P. Crawford", "etype": "editorial"},
        {"title": "Unsung Heroes in Zion's Cause", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Dependability", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Buttonholes and Fasteners", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "America Through Testing Years", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "The Abundant Life, Here and Hereafter", "author": "T. Edgar Lyon", "etype": "lesson"},
        {"title": "Constructive Use of Time", "author": "Social Science Committee", "etype": "lesson"},
        {"title": "Tomorrow Frontispiece", "author": "Berta Huish Christensen", "etype": "poem"},
        {"title": "New Year's Resolution", "author": "Caroline Eyring Miner", "etype": "poem"},
        {"title": "Pioneer Women", "author": "Olive W. Burt", "etype": "poem"},
        {"title": "Winter Night", "author": "Grace M. Candland", "etype": "poem"},
        {"title": "Birds", "author": "Marguerite Kirkham", "etype": "poem"},
        {"title": "A Mother to Her Babe", "author": "Roxana F. Hase", "etype": "poem"},
        {"title": "Winter Bouquet", "author": "Ruth H. Chadwick", "etype": "poem"},
        {"title": "Certitude", "author": "Dorothy J. Roberts", "etype": "poem"},
    ],

    ("Vol34", "No2_February_1947"): [
        {"title": "European Relief", "author": None, "etype": "article"},
        {"title": "Bishop Thorpe B. Isaacson Appointed to the Presiding Bishopric", "author": "Thomas E. McKay", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: On the River Platte II", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "February Table Decorations", "author": None, "etype": "article"},
        {"title": "Cast Thy Burden", "author": None, "etype": "fiction"},
        {"title": "Where Trails Run", "author": None, "etype": "fiction"},
        {"title": "The Tin-Can Doll", "author": None, "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Faithful to the Pioneer Heritage", "author": None, "etype": "editorial"},
        {"title": "Program for the Evening Service of Fast Sunday, March 2, 1947", "author": None, "etype": "article"},
        {"title": "Congratulations to President Amy Brown Lyman on Her Birthday February 7", "author": None, "etype": "article"},
        {"title": "General Activities and Special Programs", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "The Church of Jesus Christ of Latter-day Saints Over a Century Old", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Thirst for Knowledge", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Fashion Show", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "America, Land of All Nations", "author": "Howard R. Driggs", "etype": "lesson"},
        {"title": "Education and Recreation", "author": "T. Edgar Lyon", "etype": "lesson"},
        {"title": "Gratitude in the Home", "author": "Social Science Committee", "etype": "lesson"},
        {"title": "They Say of You Frontispiece", "author": "Berta H. Christensen", "etype": "poem"},
        {"title": "What the Letter Said", "author": "Mabel Jones Gabbott", "etype": "poem"},
        {"title": "Winter Green", "author": "Maude Blixt Trone", "etype": "poem"},
        {"title": "Wealth of Faith", "author": "Eva Willes Wangsgaard", "etype": "poem"},
        {"title": "The Skier", "author": "Margery S. Stewart", "etype": "poem"},
        {"title": "Told at Sunset", "author": "Grace Zenor Pratt", "etype": "poem"},
        {"title": "Winter Harvest", "author": "Ora Lee Parthesius", "etype": "poem"},
    ],

    ("Vol34", "No3_March_1947"): [
        {"title": "Compassionate Service the Fundamental Work of Relief Society", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "Building for Eternity", "author": "Marianne C. Sharp", "etype": "article"},
        {"title": "The Value of Relief Society Membership", "author": "Gertrude R. Garff", "etype": "article"},
        {"title": "Elder Charles A. Callis", "author": "Preston Nibley", "etype": "article"},
        {"title": "The Barren Desert Is a Fruitful Field", "author": "Louise Lee Udall", "etype": "article"},
        {"title": "Daughter of the Pioneers", "author": "Inez B. Allred", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: Handcart Pioneers", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Progressive Leadership in Music", "author": "Florence J. Madsen", "etype": "article"},
        {"title": "Herbs and Their Uses", "author": "Elizabeth Williamson", "etype": "article"},
        {"title": "The Sound of Bugles", "author": "Olive Maiben Nicholes", "etype": "fiction"},
        {"title": "If You Will Drive", "author": "Dorothy Clapp Robinson", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 2", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Proper Conduct in Church Services", "author": "Gertrude R. Garff", "etype": "editorial"},
        {"title": "Luella N. Adams and Ann P. Nibley Released From the General Board", "author": None, "etype": "article"},
        {"title": "Time for Holding Optional Sewing Class", "author": None, "etype": "article"},
        {"title": "Anniversary Programs and Other Activities", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Beacons Frontispiece", "author": "Margery S. Stewart", "etype": "poem"},
        {"title": "Sturdy March", "author": "Vernella Ames", "etype": "poem"},
        {"title": "Miracle of Spring", "author": "Gene Romolo", "etype": "poem"},
        {"title": "Who Can Say There Is No God?", "author": "Mabel Jones Gabbott", "etype": "poem"},
        {"title": "He Lived Again", "author": "Caroline Eyring Miner", "etype": "poem"},
        {"title": "Evelyn Fjeldsted", "author": None, "etype": "poem"},
        {"title": "The Awakening", "author": "Ruth H. Chadwell", "etype": "poem"},
        {"title": "The Mountain", "author": "Jeanne Tenney", "etype": "poem"},
        {"title": "March Wind", "author": "Maude Blixt Trone", "etype": "poem"},
        {"title": "Patterned By the Furrow", "author": "Eva Willes Wangsgaard", "etype": "poem"},
        {"title": "Grandmother", "author": "Eliza Carpenter", "etype": "poem"},
        {"title": "Who Makes A Garden", "author": "Della Adams Leitner", "etype": "poem"},
    ],

    ("Vol34", "No4_April_1947"): [
        {"title": "The Greatest Miracle", "author": "Spencer W. Kimball", "etype": "article"},
        {"title": "Birthday Greetings to President Smith", "author": None, "etype": "article"},
        {"title": "Latter-day Saint Pioneers in New Mexico", "author": "Estelle Webb Thomas", "etype": "article"},
        {"title": "Nature's Sculpture Work", "author": "Willard Luce", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: Handcart Pioneers II", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Breakfast Is an Important Meal", "author": "Hazel Stevens", "etype": "article"},
        {"title": "Mormonism in the Eyes of the Press: The Press Views Mormonism as a Zionist Movement", "author": "James R. Clark", "etype": "article"},
        {"title": "Select Safe Clothes", "author": "C. Elaine Ericksen", "etype": "article"},
        {"title": "Color For the Centennial Summer", "author": "Vesta P. Crawford", "etype": "article"},
        {"title": "A Reward For Cheerful Service", "author": "Lucinda M. Chidester Harrington", "etype": "article"},
        {"title": "Young Samantha", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "A Place in the Country: The Arrival", "author": "Ruby Scranton Jones", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 3", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "The Woman of the Shawl", "author": "C. Frank Steele", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "All These Things Shall Be Held in Remembrance", "author": "Vesta P. Crawford", "etype": "editorial"},
        {"title": "Relief Society Bazaars and General Activities", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Mary Magdalene Frontispiece", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Opinions", "author": "Lillian S. Smith", "etype": "poem"},
        {"title": "In Waiting", "author": "Eva Willes Wangsgaard", "etype": "poem"},
        {"title": "Prisoner", "author": "Margery S. Stewart", "etype": "poem"},
        {"title": "A Gull at Dawn", "author": "Jo Adelaide Stock", "etype": "poem"},
        {"title": "Walk a Little Way With Me", "author": "Leona Bammes Gardner", "etype": "poem"},
        {"title": "The Amaryllis", "author": "Evelyn Fjeldsted", "etype": "poem"},
        {"title": "The Challenge of a Daffodil", "author": "Wanda M. Lund", "etype": "poem"},
        {"title": "Weber River", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "Chastisement", "author": "Genevieve J. Van Wagenen", "etype": "poem"},
        {"title": "April Wisdom", "author": "Maude Blixt Trone", "etype": "poem"},
        {"title": "Recompense", "author": "Berta H. Christensen", "etype": "poem"},
        {"title": "Be Still", "author": "Olive C. Wehr", "etype": "poem"},
        {"title": "I Shall Be Glad", "author": "Jeanette P. Parry", "etype": "poem"},
    ],

    ("Vol34", "No5_May_1947"): [
        {"title": "The Mothers of the Members of the Quorum of the Twelve", "author": "Camilla E. Kimball", "etype": "article"},
        {"title": "Mothers Makers of Men", "author": "Henry D. Moyle", "etype": "article"},
        {"title": "Elder Harold B. Lee The New Apostle", "author": "Edwin Q. Cannon", "etype": "article"},
        {"title": "Elder Eldred G. Smith Named Patriarch to the Church", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "Letters to President Grant From His Mother", "author": "Rachel Grant Taylor", "etype": "article"},
        {"title": "Pioneer Cookery", "author": "Beatrice K. Ekman", "etype": "article"},
        {"title": "A Mother Builded Frontispiece", "author": "Christie Lund Coles", "etype": "poem"},
        {"title": "A Mother's Poem", "author": "Etta J. Coulam", "etype": "poem"},
        {"title": "These Things I Know", "author": "Mabel Jones Gabbott", "etype": "poem"},
        {"title": "Heights", "author": "Evelyn Fjeldsted", "etype": "poem"},
        {"title": "Gems", "author": "Alice Whitson Norton", "etype": "poem"},
        {"title": "Nostalgia", "author": "Merling Dennis Clyde", "etype": "poem"},
        {"title": "Two Figures", "author": "Eva Matson Perry", "etype": "poem"},
        {"title": "The Growing House", "author": "Erma Barney Braack", "etype": "poem"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Relief Society Magazine Subscription Price Raised to $1.50 as of July 1, 1947", "author": None, "etype": "article"},
        {"title": "Summer Work Meeting", "author": None, "etype": "article"},
        {"title": "Notes From the Field", "author": "Margaret C. Pickering", "etype": "article"},
    ],

    ("Vol34", "No6_June_1947"): [
        {"title": "The Prophet Brigham Young", "author": "William E. Stoker", "etype": "article"},
        {"title": "Contest Announcements 1947", "author": None, "etype": "article"},
        {"title": "The Art of Poetry Writing: A Symposium of Opinions", "author": None, "etype": "article"},
        {"title": "We Want to Write", "author": "Dorothy Clapp Robinson", "etype": "article"},
        {"title": "Utah Pioneer Women Poets", "author": None, "etype": "article"},
        {"title": "Busy Fingers", "author": "G. W. Staker", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: III Handcart Pioneers", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Entertaining at a Cabin in the Canyon", "author": "Rose Thomas Graham", "etype": "article"},
        {"title": "Plan for Christmas in June", "author": "Ethel Colton Smith", "etype": "article"},
        {"title": "Divine Leadership", "author": "Alice Whitson Norton", "etype": "article"},
        {"title": "It's Up to the Women", "author": "Norma Wrathall", "etype": "fiction"},
        {"title": "A Place in the Country: II The Curtains", "author": "Ruby Scranton Jones", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 5", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Fine Raiment", "author": "Vesta P. Crawford", "etype": "editorial"},
        {"title": "Instructions to Magazine Representatives and Subscribers", "author": None, "etype": "article"},
        {"title": "Relief Society Centennial Programs and Other Activities", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Song of the Wheels Frontispiece", "author": "Ora Pate Stewart", "etype": "poem"},
        {"title": "The Cycle", "author": "Agnes Just Reid", "etype": "poem"},
        {"title": "June Pageantry", "author": "Amelia Ames", "etype": "poem"},
        {"title": "Resignation", "author": "Etta S. Robbins", "etype": "poem"},
        {"title": "Transition", "author": "Margery S. Stewart", "etype": "poem"},
        {"title": "Honeymoon Garden", "author": "Blanche Kendall McKey", "etype": "poem"},
        {"title": "Sego Lilies", "author": "Evelyn Fjeldsted", "etype": "poem"},
        {"title": "June", "author": "Alice R. Rich", "etype": "poem"},
        {"title": "Perception", "author": "Clarence Edwin Flynn", "etype": "poem"},
    ],

    ("Vol34", "No7_July_1947"): [
        {"title": "Mahonri M. Young, Sculptor of This Is the Place Monument", "author": "Levi Edgar Young", "etype": "article"},
        {"title": "Birthday Greetings to Sister Augusta Winters Grant", "author": None, "etype": "article"},
        {"title": "Pioneer Stories and Incidents: Pioneer Women", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "The Arts Section of the Utah Centennial Celebration", "author": "Gail Martin", "etype": "article"},
        {"title": "Pioneer Gardenmaking", "author": "Hazel D. Moyle", "etype": "article"},
        {"title": "Call It a Day", "author": "Estelle Webb Thomas", "etype": "fiction"},
        {"title": "A Place in the Country: III. Water", "author": "Ruby Scranton Jones", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 6", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "Donation Additions to the 1946 Relief Society Magazine Honor Roll", "author": None, "etype": "article"},
        {"title": "Instructions to Magazine Representatives and Subscribers", "author": None, "etype": "article"},
        {"title": "Relief Society Centennial Programs and General Activities", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Notes on Authors of the Lessons", "author": None, "etype": "article"},
        {"title": "The Life and Ministry of the Savior", "author": None, "etype": "lesson"},
        {"title": "Preexistence and Foreordination of Christ", "author": "Don B. Colton", "etype": "lesson"},
        {"title": "Our Pioneer Heritage The Fruits of Pioneer Virtues", "author": None, "etype": "lesson"},
        {"title": "Organization", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Literature of the Doctrine and Covenants", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Introductory Lesson to Literature of the Doctrine and Covenants", "author": "Marianne C. Sharp", "etype": "lesson"},
        {"title": "Essentials in Home Training", "author": None, "etype": "lesson"},
        {"title": "Obedience", "author": "Joseph Jacobs", "etype": "lesson"},
        {"title": "Sego Lily Frontispiece", "author": "Eva Willes Wangsgaard", "etype": "poem"},
        {"title": "A Little of Mary", "author": "Josephine J. Harvey", "etype": "poem"},
        {"title": "Pioneer Woman", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "Little Pioneers", "author": "Ethel Van Hook Hopper", "etype": "poem"},
        {"title": "Covered Wagons", "author": "Beatrice Rordame Parsons", "etype": "poem"},
    ],

    ("Vol34", "No8_August_1947"): [
        {"title": "Where There's a Will: Ethel Colton Smith, New Member of the General Board", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "A Visit to the Hawaiian Islands", "author": "Donna D. Sorensen", "etype": "article"},
        {"title": "Pioneer Stories and Incidents: Oxen on the Plains", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "The Visiting Teacher", "author": "Lottie Hammer Singley", "etype": "article"},
        {"title": "How the Magazine Fortifies the Visiting Teacher", "author": "Anna B. Hart", "etype": "article"},
        {"title": "Visiting Teachers How They Traveled", "author": "Cummings", "etype": "article"},
        {"title": "Magazine Promotion", "author": "Ida Isaacson", "etype": "article"},
        {"title": "August Coolers", "author": "Sara Mills", "etype": "article"},
        {"title": "Be Gay, for Once", "author": "Blanche Kendall McKey", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 7", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "A Place in the Country IV The Chickens", "author": "Ruby Scranton Jones", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Make Home a Pleasant Place", "author": "Gertrude R. Garff", "etype": "editorial"},
        {"title": "Activities for Visiting Teachers and Special Centennial Programs", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "The Need of a Redeemer; The Antemortal Godship of Christ", "author": "Don B. Colton", "etype": "lesson"},
        {"title": "Colonization", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Musts for Success in Sewing", "author": "Work Meeting Committee", "etype": "article"},
        {"title": "Literary Values of the Doctrine and Covenants", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Essentials in Home Training", "author": "Joseph Jacobs", "etype": "lesson"},
        {"title": "One Who Waited Frontispiece", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Centennial Return", "author": "Andrew M. Andersen", "etype": "poem"},
        {"title": "The Place", "author": "Oliver K. Meservy", "etype": "poem"},
        {"title": "Evening", "author": "Nan S. Richardson", "etype": "poem"},
        {"title": "Remembrance", "author": "Lizabeth Wall", "etype": "poem"},
        {"title": "Happy Landings", "author": "Erma Young Gardiner", "etype": "poem"},
        {"title": "Our Baby", "author": "Grace Sayre", "etype": "poem"},
        {"title": "Soul Food", "author": "Rose Thomas Graham", "etype": "poem"},
        {"title": "Myra Kirkman", "author": None, "etype": "poem"},
        {"title": "Fields Of Green", "author": "Evelyn Fjeldsted", "etype": "poem"},
    ],

    ("Vol34", "No9_September_1947"): [
        {"title": "New England and the Church", "author": "William H. Reeder, Jr.", "etype": "article"},
        {"title": "Silk, Cotton, and Wool Produced in Utah", "author": "Julia A. F. Lund", "etype": "article"},
        {"title": "September Fruits", "author": "Sara Mills", "etype": "article"},
        {"title": "A Strange Ransom", "author": "Ellen Redd Bryner", "etype": "article"},
        {"title": "Always a Frontier", "author": "Christie Lund Coles", "etype": "fiction"},
        {"title": "A Place in the Country V Neighbors", "author": "Ruby Scranton Jones", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 8", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "A Testament of Liberty", "author": "Vesta P. Crawford", "etype": "editorial"},
        {"title": "Annual Relief Society General Conference", "author": None, "etype": "article"},
        {"title": "Ward Relief Society Conferences, November 2, 1947", "author": None, "etype": "article"},
        {"title": "Annual Report 1946", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Fashion Shows, Bazaars, and Other Activities", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Earthly Advent of the Christ Predicted: The Meridian of Time", "author": "Don B. Colton", "etype": "lesson"},
        {"title": "Religious Activities", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Choosing a Pattern", "author": "Jean Ridges Jennings", "etype": "article"},
        {"title": "Types of Literature Found in the Doctrine and Covenants", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Within These Cadences Frontispiece", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "Memories", "author": "Louise Sill", "etype": "poem"},
        {"title": "Union Fort Monument", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Beauty", "author": "Sylvia Probst Young", "etype": "poem"},
        {"title": "Nostalgia", "author": "Myrtle Dean", "etype": "poem"},
        {"title": "The Spinning Wheel", "author": "Mabel Jones Gabbott", "etype": "poem"},
        {"title": "Inspiration", "author": "Eva J. Lillywhite", "etype": "poem"},
        {"title": "Rhythm", "author": "Rosella F. Larkin", "etype": "poem"},
    ],

    ("Vol34", "No10_October_1947"): [
        {"title": "Seventy-fifth Birthday Year", "author": "Rosannah Cannon Irvine", "etype": "article"},
        {"title": "Utah Entertains the Governors", "author": "Edith S. Elliott", "etype": "article"},
        {"title": "Vesta P. Crawford Appointed Associate Editor of The Relief Society Magazine", "author": "Marianne C. Sharp", "etype": "article"},
        {"title": "The Gift Drawer", "author": "Ivie H. Jones", "etype": "article"},
        {"title": "Cooperative Dinners", "author": "Emily H. Bennett", "etype": "article"},
        {"title": "Vanity Stool and Hamper", "author": "Eva Willes Wangsgaard", "etype": "article"},
        {"title": "The Kidnaping", "author": "Fay Tarlock", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 9", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Diamond Jubilee of Women's Periodical", "author": "Marianne C. Sharp", "etype": "editorial"},
        {"title": "Isabel B. Callister Resigns from General Board", "author": None, "etype": "article"},
        {"title": "In Memoriam: Edith Grant Young Passes", "author": None, "etype": "article"},
        {"title": "Notes From the Field", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Gabriel's Annunciation of John and Jesus: The Babe of Bethlehem", "author": "Don B. Colton", "etype": "lesson"},
        {"title": "Social Activities", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Altering the Pattern to Suit the Figure Type", "author": "Jean Ridges Jennings", "etype": "article"},
        {"title": "Epistles of the Doctrine and Covenants", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Chastity", "author": "Joseph Jacobs", "etype": "lesson"},
        {"title": "Prayer of a Pipe Organ Frontispiece", "author": "Julia Nelson", "etype": "poem"},
        {"title": "Vignette of October", "author": "Ruby Baird Andersen", "etype": "poem"},
        {"title": "Discovery", "author": "Margery S. Stewart", "etype": "poem"},
        {"title": "The Shallow Streams", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Storm and Calm", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "Autumn Day", "author": "Christie Lund Coles", "etype": "poem"},
        {"title": "The Joy of Doing", "author": "Caroline Eyring Miner", "etype": "poem"},
        {"title": "Dusk on the Beach", "author": "Melba S. Payne", "etype": "poem"},
        {"title": "To Find To Lose", "author": "Evelyn Fjeldsted", "etype": "poem"},
    ],

    ("Vol34", "No11_November_1947"): [
        {"title": "The Joys of Welfare Service", "author": "Marion G. Romney", "etype": "article"},
        {"title": "Reading and Writing in Deseret", "author": "Anna Boss Hart", "etype": "article"},
        {"title": "Sewing in Pioneer Days", "author": "Leda Thompson Jensen", "etype": "article"},
        {"title": "Breakfasts", "author": "Sara Mills", "etype": "article"},
        {"title": "Real Bargains", "author": "Ivie H. Jones", "etype": "article"},
        {"title": "A Man Must Work", "author": "Alice Morrey Bailey", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 10", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "Christmas, Or a Reasonable Facsimile", "author": "Mabel Harmer", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Bless the Food", "author": "Vesta P. Crawford", "etype": "editorial"},
        {"title": "Fashion Shows, Singing Mothers, and Other Activities", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "The Boy of Nazareth; In the Wilderness of Judea", "author": "Don B. Colton", "etype": "lesson"},
        {"title": "Cultural Activities", "author": "Amy Brown Lyman", "etype": "lesson"},
        {"title": "Sleeve Fitting and Shoulder Pads", "author": "Jean Ridges Jennings", "etype": "article"},
        {"title": "Prayers of the Doctrine and Covenants", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "The Observance of the Sabbath Day", "author": "Joseph Jacobs", "etype": "lesson"},
        {"title": "All That Lifts to Beauty Frontispiece", "author": "Berta H. Christensen", "etype": "poem"},
        {"title": "Anchored", "author": "Andrew M. Andersen", "etype": "poem"},
        {"title": "First School", "author": "Eva Willes Wangsgaard", "etype": "poem"},
        {"title": "Thanksgiving Grace", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Confidentially", "author": "Josephine J. Harvey", "etype": "poem"},
        {"title": "Gems", "author": "Ora Pate Stewart", "etype": "poem"},
        {"title": "Thelma Ireland", "author": None, "etype": "poem"},
        {"title": "Prayer", "author": "Renie H. Littlewood", "etype": "poem"},
        {"title": "The Golden Thread", "author": "Matia McClelland Burk", "etype": "poem"},
        {"title": "Vigil", "author": "Ora Lee Parthesius", "etype": "poem"},
        {"title": "Revealed", "author": "Eunice J. Miles", "etype": "poem"},
        {"title": "On a Fiftieth Wedding Anniversary", "author": "Melva S. Payne", "etype": "poem"},
    ],

    ("Vol34", "No12_December_1947"): [
        {"title": "Plan for Financing a Relief Society Building", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "The Importance of the Family Hour", "author": "Ezra Taft Benson", "etype": "article"},
        {"title": "Velma N. Simonsen Named Second Counselor in General Presidency", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "Gertrude R. Garff Released as Counselor in General Presidency", "author": "Belle S. Spafford", "etype": "article"},
        {"title": "The Annual General Relief Society Conference", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "Make the Children Happy", "author": "Elizabeth Williamson", "etype": "article"},
        {"title": "Peace, Be Still", "author": "Marguerite J. Griffin", "etype": "article"},
        {"title": "Comments From Magazine Readers", "author": None, "etype": "article"},
        {"title": "Christmas by Emergency", "author": "Alice Morrey Bailey", "etype": "fiction"},
        {"title": "Skids for Scarlett", "author": "Grace Cozzens", "etype": "fiction"},
        {"title": "Where Trails Run Out Chapter 11", "author": "Anna Prince Redd", "etype": "fiction"},
        {"title": "Sixty Years Ago", "author": None, "etype": "article"},
        {"title": "Woman's Sphere", "author": "Ramona W. Cannon", "etype": "article"},
        {"title": "Where Peace Begins", "author": "Vesta P. Crawford", "etype": "editorial"},
        {"title": "Support the Family Hour", "author": "Marianne C. Sharp", "etype": "article"},
        {"title": "Organizations and Reorganizations of Mission and Stake Relief Societies", "author": None, "etype": "article"},
        {"title": "Watch This Month", "author": None, "etype": "article"},
        {"title": "Relief Society Centennial Programs and Other Activities", "author": "Margaret C. Pickering", "etype": "article"},
        {"title": "From Judea to Galilee; Early Incidents in Our Lord's Public Ministry", "author": "Don B. Colton", "etype": "lesson"},
        {"title": "Sewing", "author": "Jean Ridges Jennings", "etype": "article"},
        {"title": "Visions of the Doctrine and Covenants", "author": "H. Wayne Driggs", "etype": "lesson"},
        {"title": "Refinement", "author": "Joseph Jacobs", "etype": "lesson"},
        {"title": "To Him Again Frontispiece", "author": "Dorothy J. Roberts", "etype": "poem"},
        {"title": "Christmas Eve", "author": "Mary J. Morris", "etype": "poem"},
        {"title": "Winter Delight", "author": "Grace M. Candland", "etype": "poem"},
        {"title": "Immortal Song", "author": "Sadie Ollorton Clark", "etype": "poem"},
        {"title": "Christmas Prayer", "author": "Christie Lund Coles", "etype": "poem"},
        {"title": "Dilemma", "author": "Alice Whitson Norton", "etype": "poem"},
        {"title": "Winter Blossoming", "author": "Beatrice K. Ekman", "etype": "poem"},
        {"title": "Christmas Shopping", "author": "Grace Sayre", "etype": "poem"},
        {"title": "Winter Splendor", "author": "Thelma Ireland", "etype": "poem"},
        {"title": "Lights", "author": "Josephine J. Harvey", "etype": "poem"},
        {"title": "Bread and Age", "author": "Abbie R. Madsen", "etype": "poem"},
        {"title": "Legend", "author": "Ella J. Coulam", "etype": "poem"},
        {"title": "Sincerity", "author": "Evelyn Wooster Viner", "etype": "poem"},
    ],

    # ===================================================================
    # VOLUME 35 (1948) - Partial (needs months 4-12 completed data)
    # ===================================================================

    ("Vol35", "No1_January_1948"): [
        {"title": "Happy New Year!", "author": "General Presidency of Relief Society", "etype": "article"},
        {"title": "Pioneer Women", "author": "David O. McKay", "etype": "article"},
        {"title": "Award Winners Eliza Roxey Snow Memorial Prize Poem Contest", "author": None, "etype": "article"},
        {"title": "The Cherry Orchard", "author": "Katherine Fernelius Larsen", "etype": "poem"},
        {"title": "Migrant", "author": "Alice Morrey Bailey", "etype": "poem"},
        {"title": "Snow Upon the Earth Frontispiece", "author": "Christie Lund Coles", "etype": "poem"},
        {"title": "Earth's Song of the Road", "author": "C. Cameron Johns", "etype": "poem"},
        {"title": "A New Year", "author": "Clarence Edwin Flynn", "etype": "poem"},
        {"title": "Symphony", "author": "Beatrice Rordame Parsons", "etype": "poem"},
        {"title": "Caught Napping", "author": "Grace A. Woodbury", "etype": "poem"},
        {"title": "My Wealth", "author": "Julia Nelson", "etype": "poem"},
    ],

    # ===================================================================
    # VOLUME 36-40 (1949-1953)
    # NOTE: TOC data for Vol36-40 to be added when extracted
    # ===================================================================
}
