#!/usr/bin/env python3
"""
Table of Contents for Relief Society Magazine Volumes 4, 5, and 6 (1917, 1918, 1919).

These early volumes have simpler section structures than later volumes:
- Most content is articles
- "Guide Lessons" appear at the end
- "Editorial" is usually one entry per month
- Poetry may be mixed in with articles (not a separate section)
- "Notes from the Field" is a recurring section

Format: VOL{N}_TOC[(volume, issue_key)] = [entry_list]
Each entry has: title, author, etype
"""

# ============================================================
# VOLUME 4 (1917)
# ============================================================

VOL4_TOC = {
    ("Vol4", "No1_January_1917"): [
        {"title": "Relief Society Calendar", "author": None, "etype": "article"},
        {"title": "General Board of the Relief Society", "author": None, "etype": "article"},
        {"title": "New Year Epistle", "author": None, "etype": "article"},
        {"title": "Mrs. Alice Merrill Home", "author": None, "etype": "article"},
        {"title": "Life's Wintry Way", "author": "Marie Jensen", "etype": "poem"},
        {"title": "A Forceful Business Venture", "author": "Ida Stewart Peay", "etype": "article"},
        {"title": "Isobel Gives a New Year's Dinner", "author": "Diana Parrish", "etype": "article"},
        {"title": "Mothers in Israel", "author": "Mary A. S. Winters", "etype": "article"},
        {"title": "Mother", "author": "Alfred Lambourne", "etype": "poem"},
        {"title": "Home Evening Entertainment", "author": "Morg", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "A Call to the Women of the Church", "author": None, "etype": "editorial"},
        {"title": "High Cost of Living", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No2_February_1917"): [
        {"title": "Things Worth While", "author": "Jessie Sundwall", "etype": "poem"},
        {"title": "Francis Marion Lyman", "author": None, "etype": "article"},
        {"title": "President Heber J. Grant", "author": None, "etype": "article"},
        {"title": "Francis Marion Lyman", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "Birth Control", "author": None, "etype": "article"},
        {"title": "Our Lovely Human Heritage", "author": "President Emmeline B. Wells", "etype": "article"},
        {"title": "Mothers in Israel", "author": "Mary A. S. Winters", "etype": "article"},
        {"title": "An Incident of Faith", "author": None, "etype": "article"},
        {"title": "Washington's Vision", "author": None, "etype": "article"},
        {"title": "February Entertainment", "author": "Morag", "etype": "article"},
        {"title": "Too Busy", "author": "Mrs. Parley Nelson", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Memories", "author": "Marie Jensen", "etype": "poem"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "The Relief Society in Its Attitude to Dress and Social Customs", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No3_March_1917"): [
        {"title": "The Relief Society Sisters", "author": "Maud Baggarley", "etype": "poem"},
        {"title": "An Interesting Outgrowth of the Relief Society in Nauvoo", "author": "J. M. Monroe", "etype": "article"},
        {"title": "Home of Heber C. Kimball, Nauvoo", "author": None, "etype": "article"},
        {"title": "Mothers in Israel", "author": "Mary Ann Stearns Winters", "etype": "article"},
        {"title": "An Interesting Occurrence in Canada", "author": "Edward J. Wood", "etype": "article"},
        {"title": "A Morning Reverie", "author": "Annie D. S. Palmer", "etype": "article"},
        {"title": "Anniversary Day Programs", "author": None, "etype": "article"},
        {"title": "Home Evening Entertainment", "author": "Morag", "etype": "article"},
        {"title": "The Music Page", "author": None, "etype": "article"},
        {"title": "Admiral George Dewey and Homer Davenport", "author": "Alice Louise Reynolds", "etype": "article"},
        {"title": "The Relief Society Ward President", "author": "Annie Wells Cannon", "etype": "article"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Our Annual Day", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No4_April_1917"): [
        {"title": "April", "author": "Lucy May Green", "etype": "poem"},
        {"title": "Font for the Hawaiian Temple", "author": "Avard Fairbanks", "etype": "article"},
        {"title": "Latter-day Temples", "author": None, "etype": "article"},
        {"title": "Birthday Celebration of our Honored President", "author": None, "etype": "article"},
        {"title": "Our New Board Member", "author": None, "etype": "article"},
        {"title": "Winning the Man's Mother", "author": "Ida Stewart Peay", "etype": "article"},
        {"title": "April Entertainment", "author": "Morag", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Social Work", "author": None, "etype": "article"},
        {"title": "On the Way", "author": "Mrs. Parley Nelson", "etype": "poem"},
        {"title": "Spiritual Manifestations", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No5_May_1917"): [
        {"title": "My Masterpiece", "author": "Elsie C. Carroll", "etype": "poem"},
        {"title": "Mothers in Israel", "author": None, "etype": "article"},
        {"title": "Departed Spirits", "author": "Laura Moench Jenkins", "etype": "poem"},
        {"title": "Children's Problems", "author": "Lucy Wright Snow", "etype": "article"},
        {"title": "May Entertainments", "author": "Morag", "etype": "article"},
        {"title": "A Brave Friend", "author": None, "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "War is Upon Us", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No6_June_1917"): [
        {"title": "The Star-Spangled Banner", "author": None, "etype": "article"},
        {"title": "A Widowed Mother to her Son", "author": "Alfred Lambourne", "etype": "poem"},
        {"title": "Another Widowed Mother", "author": None, "etype": "article"},
        {"title": "General Conference of the Relief Society", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "The Disease Germ in Utah", "author": None, "etype": "article"},
        {"title": "June Entertainments", "author": "Morag", "etype": "article"},
        {"title": "Pin Money Suggestions", "author": "Morag", "etype": "article"},
        {"title": "Evolution of the American Flag", "author": "A. B. L.", "etype": "article"},
        {"title": "Common Sense", "author": None, "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Our Conference", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No7_July_1917"): [
        {"title": "In Memory of 1847", "author": "Hazel Washburn", "etype": "poem"},
        {"title": "Epistle to the Relief Society Concerning these War Times", "author": None, "etype": "article"},
        {"title": "First Winter in Salt Lake City, 1847", "author": "Diantha Lowry Reid", "etype": "article"},
        {"title": "What Women Can Do in Canning", "author": None, "etype": "article"},
        {"title": "Mothers in Israel", "author": "Mary A. S. Winters", "etype": "article"},
        {"title": "Object, Origin and Destiny of Women", "author": "Prest. John Taylor", "etype": "article"},
        {"title": "Are We Wise?", "author": "Grace Jacobson", "etype": "poem"},
        {"title": "Mother Entertains", "author": "Diantha Parrish", "etype": "article"},
        {"title": "How to Make a Homemade Fireless Cooker", "author": None, "etype": "article"},
        {"title": "The Iceless Refrigerator", "author": None, "etype": "article"},
        {"title": "Home Entertainments", "author": "Morag", "etype": "article"},
        {"title": "President Joseph F. Smith on Card Playing", "author": None, "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No8_August_1917"): [
        {"title": "Laudamus", "author": "Mrs. Carrie S. Thomas", "etype": "poem"},
        {"title": "Mrs. Priscilla Paul Jennings", "author": None, "etype": "article"},
        {"title": "Mark Twain's Observations", "author": None, "etype": "article"},
        {"title": "Mothers in Israel", "author": "Mary A. S. Winters", "etype": "article"},
        {"title": "Red Cross Work in the Relief Society", "author": None, "etype": "article"},
        {"title": "Early Amusements in Utah", "author": "Sarah Jane Rich Miller", "etype": "article"},
        {"title": "Zion", "author": "Maud Dobson", "etype": "poem"},
        {"title": "August Entertainment", "author": "Morag", "etype": "article"},
        {"title": "Industrial Education in the Brigham Young University", "author": None, "etype": "article"},
        {"title": "The New American Army Song", "author": None, "etype": "article"},
        {"title": "Does it Pay?", "author": "Marie Jensen", "etype": "poem"},
        {"title": "Mother Love", "author": "Sophie Valentine", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No9_September_1917"): [
        {"title": "A Bouquet and a Sentiment", "author": "Lula Greene Richards", "etype": "poem"},
        {"title": "A Friend of the Helpless Dead", "author": None, "etype": "article"},
        {"title": "Reclaimed", "author": "Coral J. Black", "etype": "poem"},
        {"title": "The Red Cross", "author": "Young Gates", "etype": "article"},
        {"title": "The Widow's Mite", "author": "Laura Moench Jenkins", "etype": "article"},
        {"title": "Real Economy in the Home", "author": "Clara Fagangren", "etype": "article"},
        {"title": "Home Entertainment", "author": "Morag", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No10_October_1917"): [
        {"title": "I Ought to Know", "author": "Annie D. Palmer", "etype": "poem"},
        {"title": "Conservation as Practiced by the Women of the Relief Society", "author": None, "etype": "article"},
        {"title": "The Magic of Song", "author": "Mrs. Parley Nelson", "etype": "poem"},
        {"title": "Our Boys in France", "author": None, "etype": "article"},
        {"title": "Somewhere", "author": "Annie R. Roberts", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Current Events", "author": "James H. Anderson", "etype": "article"},
        {"title": "Are You Conserving Yourself?", "author": None, "etype": "editorial"},
        {"title": "Book Review", "author": None, "etype": "article"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No11_November_1917"): [
        {"title": "Your Laugh", "author": "Margaret Whitehead Young", "etype": "poem"},
        {"title": "Mothers in Israel", "author": None, "etype": "article"},
        {"title": "The Historical Office of the First Presidency", "author": None, "etype": "article"},
        {"title": "Making a Husband Out of a Man", "author": "Helen Rowland", "etype": "article"},
        {"title": "Her Prophecy and Its Fulfilment", "author": "Lucy May Green", "etype": "article"},
        {"title": "Parents' Problems", "author": "Lucy Wright Snow", "etype": "article"},
        {"title": "Home Entertainment", "author": "Morag", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Our Thanksgiving Debts", "author": None, "etype": "editorial"},
        {"title": "Liberty Bonds", "author": None, "etype": "editorial"},
        {"title": "L. D. S. U. School of Music", "author": None, "etype": "article"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol4", "No12_December_1917"): [
        {"title": "Christmas", "author": "Alfred Lambourne", "etype": "poem"},
        {"title": "A Tribute to the Birthday of the Prophet Joseph Smith", "author": "Eliza R. Snow", "etype": "poem"},
        {"title": "General Conference of Relief Society", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Mother's Christmas", "author": "Diana Parrish", "etype": "article"},
        {"title": "Unusual Mothers", "author": None, "etype": "article"},
        {"title": "The Close of the Year", "author": None, "etype": "article"},
        {"title": "The Red Cross Conference in Denver", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Mothers in Israel", "author": None, "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "My Christmas Musings", "author": "Hazel S. Washburn", "etype": "poem"},
        {"title": "December Entertainment", "author": "Morag", "etype": "article"},
        {"title": "There's a Way Out", "author": "Maud Baggarley", "etype": "poem"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Book Reviews", "author": None, "etype": "article"},
        {"title": "My Christmas Prayer", "author": None, "etype": "poem"},
        {"title": "A Word of Counsel - Signs of the Times", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
}

# ============================================================
# VOLUME 5 (1918)
# ============================================================

VOL5_TOC = {
    ("Vol5", "No1_January_1918"): [
        {"title": "Old Glory", "author": "George H. Brimhall", "etype": "poem"},
        {"title": "Revolutionary Patriots", "author": None, "etype": "article"},
        {"title": "If", "author": "Mrs. Parley Nelson", "etype": "poem"},
        {"title": "Mother Takes Up the New Year's Burden", "author": "Diana Parrish", "etype": "article"},
        {"title": "Mothers in Israel", "author": None, "etype": "article"},
        {"title": "Cecelia", "author": "Alfred Lambourne", "etype": "poem"},
        {"title": "Unusual Mothers", "author": None, "etype": "article"},
        {"title": "A 200 Year Calendar", "author": None, "etype": "article"},
        {"title": "If We Could See the End", "author": "Annie D. Palmer", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Only a Volunteer", "author": None, "etype": "article"},
        {"title": "Fruits of Endeavor", "author": "Ruth Moench Bell", "etype": "article"},
        {"title": "Trust Yet a Little While", "author": "Maud Baggarley", "etype": "poem"},
        {"title": "Our Patriotic Work", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "The New Year Relief Society Prayer", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
        {"title": "Peace I Leave with You", "author": "Lucy May Green", "etype": "poem"},
    ],
    ("Vol5", "No2_February_1918"): [
        {"title": "My Baby", "author": "Sophy Ricks Saurey", "etype": "poem"},
        {"title": "Ex-President Roosevelt Congratulates American Mothers", "author": None, "etype": "article"},
        {"title": "If I Could Live My Life Again", "author": "Mrs. Parley Nelson", "etype": "poem"},
        {"title": "The Gospel Among the Lamanites", "author": None, "etype": "article"},
        {"title": "True Friends", "author": "Edith McClendon", "etype": "poem"},
        {"title": "Mother's Valentine", "author": "Diana Parrish", "etype": "article"},
        {"title": "February Home Entertainment", "author": "Morag", "etype": "article"},
        {"title": "Mrs. Priscilla P. Jennings", "author": None, "etype": "article"},
        {"title": "The Essential", "author": "Nephi Anderson", "etype": "article"},
        {"title": "War Economy in Dress", "author": "Lillian H. Cannon", "etype": "article"},
        {"title": "Patriotic Department", "author": "Mrs. Clarissa Smith Williams", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "O War, Where is Our Fear of Thee", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol5", "No3_March_1918"): [
        {"title": "To President Joseph F. Smith, his family and all Mourners", "author": "L. Lula Greene Richards", "etype": "poem"},
        {"title": "The Passing of Apostle Hyrum M. Smith", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Dreamland", "author": "Laura Moench Jenkins", "etype": "poem"},
        {"title": "The Other Side", "author": "Lucy May Green", "etype": "article"},
        {"title": "Unusual Mothers", "author": None, "etype": "article"},
        {"title": "Suggestive Programs for Anniversary Day", "author": "Morag", "etype": "article"},
        {"title": "Integrity and Personal Loyalty", "author": "Laura J. Adamson", "etype": "article"},
        {"title": "Our Music Book", "author": None, "etype": "article"},
        {"title": "The St. George Temple", "author": "C. L. Walker", "etype": "poem"},
        {"title": "Patriotic Department", "author": "Mrs. Clarissa Smith Williams", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Food Poisoning", "author": "J. E. Greaves", "etype": "article"},
        {"title": "War Economy in Shoes", "author": "Lillian H. Cannon", "etype": "article"},
        {"title": "The Ship of Song", "author": "Hazel S. Washburn", "etype": "poem"},
        {"title": "Keep Your Eye on the Mark", "author": None, "etype": "editorial"},
        {"title": "Keep on Keeping on", "author": "Annie G. Lauritzen", "etype": "poem"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
        {"title": "The Magic of Song", "author": "Mrs. Parley Nielson, Lucy May Green", "etype": "article"},
    ],
    ("Vol5", "No4_April_1918"): [
        {"title": "Charity", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Our Relief Society Stake Presidents", "author": "Susa Young Gates", "etype": "article"},
        {"title": "A Quitter - Almost", "author": "Edna Coray", "etype": "article"},
        {"title": "Trust Yet a Little While", "author": "Maud Baggarley", "etype": "poem"},
        {"title": "Music", "author": "Brigham Cecil Gates", "etype": "article"},
        {"title": "Father Has an Inning", "author": "Diana Parrish", "etype": "article"},
        {"title": "A Utah War Romance", "author": None, "etype": "article"},
        {"title": "Home Entertainment", "author": "Morag", "etype": "article"},
        {"title": "Unusual Mothers", "author": None, "etype": "article"},
        {"title": "War Economy in Clothes", "author": None, "etype": "article"},
        {"title": "Patriotic Department", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "President Emmeline B. Wells Lighting Candles on her Birthday Cake", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Democracy Must be Made Safe for the World", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
        {"title": "The Gospel Standard", "author": "B. Cecil Gates", "etype": "article"},
    ],
    ("Vol5", "No5_May_1918"): [
        {"title": "Resurrection", "author": "Lucy S. Burnham", "etype": "poem"},
        {"title": "The Welding Link", "author": "Nephi Anderson", "etype": "article"},
        {"title": "To My Mother in Israel", "author": "Lucy May Green", "etype": "poem"},
        {"title": "Unusual Mothers", "author": None, "etype": "article"},
        {"title": "General Conference of the Relief Society", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Patriotic Department", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol5", "No6_June_1918"): [
        {"title": "A Lament", "author": "Lula Greene Richards", "etype": "poem"},
        {"title": "General Conference of the Relief Society", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol5", "No7_July_1918"): [
        {"title": "Sentiments", "author": "Emma Schrimshaw", "etype": "poem"},
        {"title": "Relief Society Work in the Missions", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Jared of Nain", "author": "L. Lula Greene Richards", "etype": "article"},
        {"title": "Unusual Mothers", "author": None, "etype": "article"},
        {"title": "July Entertainments", "author": "Morag", "etype": "article"},
        {"title": "Home Economics Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Patriotic Department", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "Red Cross Workers", "author": "Louisa M. Johnson", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "In the Work Not of the World", "author": None, "etype": "editorial"},
    ],
    ("Vol5", "No8_August_1918"): [
        {"title": "Chart of Solomon's Temple", "author": None, "etype": "article"},
        {"title": "Jerusalem Restored", "author": "Jas. H. Anderson", "etype": "article"},
        {"title": "The Temple in Jerusalem", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Little Blue Flowers", "author": "Maud Baggarley", "etype": "poem"},
        {"title": "Jerusalem, the City of Cities", "author": "Lula Greene Richards", "etype": "article"},
        {"title": "Apostrophe to Jerusalem", "author": "Eliza R. Snow", "etype": "poem"},
        {"title": "A Prayer for the Nations", "author": "Annie G. Lauritzen", "etype": "poem"},
        {"title": "Child Welfare Problems", "author": "Lucy Wright Snow", "etype": "article"},
        {"title": "Home Entertainments", "author": None, "etype": "article"},
        {"title": "Patriotic Department", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "Home Economics Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Current Topics", "author": "Jas. H. Anderson", "etype": "article"},
        {"title": "Unusual Mothers", "author": None, "etype": "article"},
        {"title": "The Return of the Jews", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol5", "No9_September_1918"): [
        {"title": "Mothers in Israel", "author": "Coral J. Black", "etype": "poem"},
        {"title": "Women Who Have Lighted Pioneer Home Fires", "author": None, "etype": "article"},
        {"title": "A Short Biography of Mrs. Rhoda Eldredge Merrill", "author": None, "etype": "article"},
        {"title": "Rags and Realities", "author": "Ruth Moench Bell", "etype": "article"},
        {"title": "Retrenchment in Clothes Inaugurated", "author": None, "etype": "article"},
        {"title": "The Cloud", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "When Mother attended Sunday School", "author": "Clara S. Fagergren", "etype": "article"},
        {"title": "Home Entertainments for September", "author": "Morag", "etype": "article"},
        {"title": "Home Economic Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Patriotic Department", "author": "Clarissa Smith William", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
        {"title": "Take Time", "author": "Mrs. Effie Rowley", "etype": "poem"},
    ],
    ("Vol5", "No10_October_1918"): [
        {"title": "I'll Go Where You Want Me to Go", "author": "Hazel Washburn", "etype": "poem"},
        {"title": "Our Biographical Number", "author": None, "etype": "article"},
        {"title": "Lines to Sister Rowena M. Whipple", "author": "Maude C. Oliver", "etype": "poem"},
        {"title": "Unusual Mothers", "author": None, "etype": "article"},
        {"title": "The Influence of Music", "author": "Lucy May Green", "etype": "article"},
        {"title": "War Time Entertainments", "author": "Morag", "etype": "article"},
        {"title": "Patriotic Department", "author": "Clarissa Smith Williams", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Report of the Murdock Relief Society", "author": "Sadie Shepherd Maeser", "etype": "article"},
        {"title": "Home Science Department", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol5", "No11_November_1918"): [
        {"title": "Thanksgiving", "author": "Mary Foster Gibbs", "etype": "poem"},
        {"title": "Lo, the Poor, Rich Indian", "author": None, "etype": "article"},
        {"title": "The Vision", "author": "Elsie C. Carroll", "etype": "article"},
        {"title": "Aunt Jane's Thanksgiving", "author": "Mrs. Parley Nelson", "etype": "article"},
        {"title": "Obesity", "author": "Raphael S. Olson, M. D.", "etype": "article"},
        {"title": "Guidance of Children", "author": "Lucy Wright Snow", "etype": "article"},
        {"title": "Patriotic Department", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol5", "No12_December_1918"): [
        {"title": "Humanity's Song", "author": "Maud Boggarsley", "etype": "poem"},
        {"title": "General Conference of Relief Society", "author": None, "etype": "article"},
        {"title": "We Are All God's Children", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Salvation for the Living and the Dead", "author": "Joseph F. Smith", "etype": "article"},
        {"title": "In Paradise", "author": "Sophia Valentine", "etype": "poem"},
        {"title": "A Tear of Love", "author": "Annie G. Lauritzen", "etype": "poem"},
        {"title": "A Christmas Sonnet", "author": "L. Lula Greene Richards", "etype": "poem"},
        {"title": "Mother's Christmas Story", "author": "Nephi Anderson", "etype": "article"},
        {"title": "Mothers and Grandmothers and Great-grandmothers in Israel", "author": None, "etype": "article"},
        {"title": "Shall Christmas Giving be Dispensed with in Time of War?", "author": "Lucy Wright Snow", "etype": "article"},
        {"title": "Christmas Suggestions", "author": "Morag", "etype": "article"},
        {"title": "How to Stimulate Discussion", "author": "Gweneth W. Gibbs", "etype": "article"},
        {"title": "Home Science Department", "author": None, "etype": "article"},
        {"title": "Current Topics", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
}

# ============================================================
# VOLUME 6 (1919)
# ============================================================

VOL6_TOC = {
    ("Vol6", "No1_January_1919"): [
        {"title": "Thou Dost Not Weep to Weep Alone", "author": "Eliza R. Snow", "etype": "poem"},
        {"title": "In Memoriam: President Joseph F. Smith", "author": None, "etype": "article"},
        {"title": "Sentiments from the Presidency and General Board of the Relief Society", "author": None, "etype": "article"},
        {"title": "Appreciation from the Three Leading Women of the Church", "author": None, "etype": "article"},
        {"title": "Vision of the Redemption of the Dead", "author": None, "etype": "article"},
        {"title": "General John J. Pershing", "author": "Mary Foster Gibbs", "etype": "article"},
        {"title": "To the Departed Year 1918", "author": "Mrs. Parley Nelson", "etype": "poem"},
        {"title": "Lines to a Tree in Winter", "author": None, "etype": "poem"},
        {"title": "Heart of the Household", "author": "Ruth Moench Bell", "etype": "article"},
        {"title": "Conservation Cook Book", "author": None, "etype": "article"},
        {"title": "Our Indian Cousins", "author": "C. L. Christensen", "etype": "article"},
        {"title": "Humility", "author": "Emily Hill Woodmansee", "etype": "poem"},
        {"title": "The Home Coming", "author": "L. Lula Greene Richards", "etype": "poem"},
        {"title": "Construction and Reconstruction in the Home", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "Official Round Table", "author": "Clarissa S. Williams, Amy Brown Lyman", "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol6", "No2_February_1919"): [
        {"title": "My Work", "author": "Maud Baggarley", "etype": "poem"},
        {"title": "A Business Man's Appreciation of President Heber J. Grant", "author": "Horace G. Whitney", "etype": "article"},
        {"title": "President Anthon H. Lund", "author": "John A. Widtsoe", "etype": "article"},
        {"title": "President Charles W. Penrose", "author": "Joseph F. Smith", "etype": "article"},
        {"title": "Elder Rudger Clawson", "author": None, "etype": "article"},
        {"title": "Be Ye of Good Cheer", "author": "Elsie E. Barrett", "etype": "poem"},
        {"title": "The New General Superintendency of Sunday Schools", "author": "William A. Morton", "etype": "article"},
        {"title": "The New General Superintendency of the Y. M. M. I. A.", "author": "Moroni Snow", "etype": "article"},
        {"title": "To a Sleeping Child", "author": "A. B. Christenson", "etype": "poem"},
        {"title": "Our Indian Cousins", "author": "C. L. Christensen", "etype": "article"},
        {"title": "The Blessedness of Pure Young Love", "author": "L. Lula Greene Richards", "etype": "poem"},
        {"title": "For Time and Eternity", "author": "Lucy May Green", "etype": "article"},
        {"title": "Lines to a Mother in Israel", "author": "Alice Foutz", "etype": "poem"},
        {"title": "Stick to Your Ideals", "author": "Elizabeth McKay Hill", "etype": "article"},
        {"title": "The Official Round Table", "author": "Clarissa Smith Williams and Amy Brown Lyman", "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": "Jannette A. Hyde", "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol6", "No3_March_1919"): [
        {"title": "In the Prison Houses", "author": "Mazel Gardner Pancake", "etype": "poem"},
        {"title": "Story of the Organization of the Relief Society", "author": None, "etype": "article"},
        {"title": "Our Indian Cousins", "author": "Melvin J. Ballard", "etype": "article"},
        {"title": "Bending the Twig", "author": "Elsie C. Carroll", "etype": "poem"},
        {"title": "The Inner Light", "author": "Lucy May Green", "etype": "poem"},
        {"title": "Two Faith-Promoting Incidents", "author": "Annie G. Lauritzen", "etype": "article"},
        {"title": "At the Temple Gates", "author": "Mary Foster Gibbs", "etype": "poem"},
        {"title": "The Years", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Let's Make a Garden", "author": "Morag", "etype": "article"},
        {"title": "Suggestions for Anniversary Day", "author": None, "etype": "article"},
        {"title": "The Official Round Table", "author": "Clarissa Smith Williams and Amy Brown Lyman", "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol6", "No4_April_1919"): [
        {"title": "The Last Days", "author": "Maud Baggarley", "etype": "poem"},
        {"title": "The Passover and the Lord's Supper", "author": "Mary Foster Gibbs", "etype": "article"},
        {"title": "Little Son", "author": "Bessie Van Wagenen", "etype": "poem"},
        {"title": "The Funny-Bone Route", "author": "Ruth Moench Bell", "etype": "article"},
        {"title": "Our Indian Cousins", "author": None, "etype": "article"},
        {"title": "Planting Trees this Spring", "author": None, "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "The Official Round Table", "author": "Clarissa Smith Williams and Amy Brown Lyman", "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol6", "No5_May_1919"): [
        {"title": "Mother", "author": "Joseph H. Smart", "etype": "poem"},
        {"title": "The Month of Mothers", "author": None, "etype": "article"},
        {"title": "Mothers of Our Leaders", "author": None, "etype": "article"},
        {"title": "Golden Wedding of Mr. & Mrs. Charles W. Nibley", "author": None, "etype": "article"},
        {"title": "Lines for a Golden Wedding Day", "author": "Mary Foster Gibbs", "etype": "poem"},
        {"title": "Municipal Kitchens in England", "author": "Joseph A. West", "etype": "article"},
        {"title": "A Lover of Grape Vines", "author": "Frank R. Arnold", "etype": "article"},
        {"title": "Guidance of Children - Family Organization", "author": "Lucy Wright Snow", "etype": "article"},
        {"title": "Real Economy in the Home", "author": "Clara Fagangren", "etype": "article"},
        {"title": "Rainbows on War Clouds", "author": "Col. James L. Hughes", "etype": "article"},
        {"title": "The Garden in May", "author": "Morag", "etype": "article"},
        {"title": "The Angel Azrael", "author": "Sarah L. Tenny", "etype": "poem"},
        {"title": "The Official Round Table", "author": "Clarissa Smith Williams and Amy Brown Lyman", "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Modern Superstition", "author": None, "etype": "editorial"},
    ],
    ("Vol6", "No6_June_1919"): [
        {"title": "Reconstruction", "author": None, "etype": "editorial"},
        {"title": "Germs and Disease", "author": "Dr. Martin P. Henderson", "etype": "article"},
        {"title": "The House Fly", "author": "Dr. Martin P. Henderson", "etype": "article"},
        {"title": "O My Father", "author": "Thomas Durham, Eliza R. Snow", "etype": "article"},
    ],
    ("Vol6", "No7_July_1919"): [
        {"title": "Prisoners of the Pit", "author": "Mabel Gardner Pancake", "etype": "poem"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": None, "etype": "article"},
        {"title": "Caution", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Teachers' Training Course", "author": None, "etype": "editorial"},
        {"title": "Summer Lesson in Hygiene: How to Keep Well", "author": "Dr. Samuel H. Allen", "etype": "article"},
        {"title": "Summer Lesson in Hygiene: How to Keep Baby Well", "author": "Dr. Raphael S. Olsen", "etype": "article"},
        {"title": "Diet Needs", "author": None, "etype": "article"},
    ],
    ("Vol6", "No8_August_1919"): [
        {"title": "Peace, Troubled Heart", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Relief Society Conference Minutes", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Reminiscences of Margaret Gay Judd Clawson", "author": None, "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol6", "No9_September_1919"): [
        {"title": "The Records of Our Dead", "author": "Lula Greene Richards", "etype": "poem"},
        {"title": "Remarks Made at R. S. Conference", "author": "Prest. Heber J. Grant", "etype": "article"},
        {"title": "Reminiscences of Margaret Judd Clawson", "author": None, "etype": "article"},
        {"title": "His Wife's Mother-in-Law", "author": "Ruth Moench Bell", "etype": "article"},
        {"title": "Objections to Temple Work", "author": "Joseph A. West", "etype": "article"},
        {"title": "What's the Price?", "author": "Mary Foster Gibbs", "etype": "poem"},
        {"title": "To My Friend", "author": "Lucy May Green", "etype": "poem"},
        {"title": "The Library of the Genealogical Society", "author": None, "etype": "article"},
        {"title": "The Garden in September", "author": None, "etype": "article"},
        {"title": "The Round Table", "author": None, "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": None, "etype": "article"},
        {"title": "Dream Pictures", "author": "Gen. D. A. Utter", "etype": "poem"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Are We Always Honest?", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol6", "No10_October_1919"): [
        {"title": "My Neighbor and I", "author": "Elsie C. Carroll", "etype": "poem"},
        {"title": "Beyond Arsareth", "author": "Nephi Anderson", "etype": "article"},
        {"title": "The Woman's Relief Society", "author": "Dr. James E. Talmage", "etype": "article"},
        {"title": "A Whiff of Ether", "author": "Lucy May Green", "etype": "article"},
        {"title": "Let There Be Light", "author": "J. Lloyd Woodruff, M. D.", "etype": "article"},
        {"title": "The Supply of Practical Nurses", "author": None, "etype": "article"},
        {"title": "Influenza and the Coming Season", "author": "Dr. A. Cyril Callister", "etype": "article"},
        {"title": "To a Lark", "author": "Joseph Hunt Stanford", "etype": "poem"},
        {"title": "Look Your Part", "author": "Morag", "etype": "article"},
        {"title": "New Book on Mexico", "author": None, "etype": "article"},
        {"title": "Cally", "author": "Lucy S. Burnham", "etype": "article"},
        {"title": "My Prayer", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Apostrophe to an Apron", "author": "Nellie B. Foote", "etype": "poem"},
        {"title": "The Cigarette Evil", "author": None, "etype": "article"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": None, "etype": "article"},
        {"title": "A Woman's Prayer", "author": "Mrs. Parley Nelson", "etype": "poem"},
        {"title": "On the Watch Tower", "author": None, "etype": "article"},
        {"title": "The League of Nations", "author": None, "etype": "editorial"},
        {"title": "The Peace of the Morning", "author": "Maude Baggarley", "etype": "poem"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol6", "No11_November_1919"): [
        {"title": "Our God and Friend", "author": "L. Lula Greene Richards", "etype": "poem"},
        {"title": "Temples", "author": None, "etype": "article"},
        {"title": "Beyond Arsareth", "author": "Nephi Anderson", "etype": "article"},
        {"title": "Prayer", "author": "D. H. Utter", "etype": "poem"},
        {"title": "Emancipation of Margaret", "author": "Bryce C.", "etype": "article"},
        {"title": "The Dream Wife", "author": "Frank Steele", "etype": "article"},
        {"title": "The November Garden", "author": "Morag", "etype": "article"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "Construction and Reconstruction in the Home", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": None, "etype": "article"},
        {"title": "The False and the True", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
    ("Vol6", "No12_December_1919"): [
        {"title": "A Christmas Lullaby", "author": "Hazel S. Washburn", "etype": "poem"},
        {"title": "General Relief Society Conference", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Vera", "author": "Grace Ingles Frost", "etype": "article"},
        {"title": "Buddhist Temples", "author": "Mary Foster Gibbs", "etype": "article"},
        {"title": "Today", "author": "Bertha A. Kleinman", "etype": "poem"},
        {"title": "Beyond Arsareth", "author": "Nephi Anderson", "etype": "article"},
        {"title": "Our Christmas Testimony", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],
}
