"""
Table of Contents for Relief Society Magazine Volumes 7-9 (1920-1922)
Manually extracted from cleaned data files.

Format: VOL7_TOC, VOL8_TOC, VOL9_TOC = { ("VolN", "NoX_Month_Year"): [entries], ... }
Each entry: {"title": str, "author": str or None, "etype": str}

etype values:
  - "article" for most entries (including Notes from the Field, Watch Tower, Round Table, etc.)
  - "editorial" for editorials
  - "poem" for poetry
  - "lesson" for Guide Lessons
  - "fiction" for serialized fiction / short stories
"""

# ===================================================================
# VOLUME 7 (1920)
# ===================================================================

VOL7_TOC = {
    ("Vol7", "No1_January_1920"): [
        {"title": "Happy Glad New Year", "author": "Lucy May Green", "etype": "poem"},
        {"title": "Edna May", "author": "Davis", "etype": "article"},
        {"title": "A Moment of Peace", "author": "Harriet A. Preston", "etype": "article"},
        {"title": "Beyond Arsareth", "author": "Nephi Anderson", "etype": "fiction"},
        {"title": "Being Nobody", "author": "Clara S. Fagergren", "etype": "article"},
        {"title": "The Secret Doors to Childhood", "author": "Ida Smoot Dusenberry", "etype": "article"},
        {"title": "Dee Hospital", "author": None, "etype": "article"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: The Discipline of Opposition in this Newest Year of 1920", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],

    ("Vol7", "No2_February_1920"): [
        {"title": "Emmeline B. Wells", "author": None, "etype": "article"},
        {"title": "Jedediah M. Grant", "author": None, "etype": "article"},
        {"title": "What Do We Know of the Other Side?", "author": None, "etype": "article"},
        {"title": "Dedication of the Hawaiian Temple", "author": None, "etype": "article"},
        {"title": "Promoted", "author": "L. Lula Green Richards", "etype": "poem"},
        {"title": "The Will and the Way", "author": "Ida Smoot Dusenberry", "etype": "article"},
        {"title": "Beyond Arsareth", "author": "Nephi Anderson", "etype": "fiction"},
        {"title": "Oh Lad O'Mine", "author": "Annie Wells Cannon", "etype": "poem"},
        {"title": "Mrs. Annie Wells Cannon", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "Editorial: The Discipline of Fear", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],

    ("Vol7", "No3_March_1920"): [
        {"title": "To the Female Relief Society", "author": None, "etype": "article"},
        {"title": "The Five General Presidents of the Relief Society", "author": None, "etype": "article"},
        {"title": "The White Begonia", "author": "Lucy May Green", "etype": "poem"},
        {"title": "A Message to Mothers", "author": "Ida Smoot Dusenberry", "etype": "article"},
        {"title": "Home Problems", "author": "Jennette A. Hyde", "etype": "article"},
        {"title": "My Hero and Heroine", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Beyond Arsareth", "author": "Nephi Anderson", "etype": "fiction"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: The Discipline of Obedience", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
        {"title": "A Tribute", "author": None, "etype": "article"},
        {"title": "Dee Hospital", "author": None, "etype": "article"},
    ],

    ("Vol7", "No4_April_1920"): [
        {"title": "Opening the Gate Beautiful to Women", "author": None, "etype": "article"},
        {"title": "Treating the Rumor Germ", "author": None, "etype": "article"},
        {"title": "Regarding Salvation for the Dead", "author": None, "etype": "article"},
        {"title": "Beyond Arsareth", "author": None, "etype": "fiction"},
        {"title": "Paradise of Childhood", "author": None, "etype": "article"},
        {"title": "Blue Peaks of the Soul", "author": None, "etype": "poem"},
        {"title": "Notes from the Field", "author": None, "etype": "article"},
        {"title": "Official Round Table", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": None, "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
        {"title": "Song", "author": None, "etype": "poem"},
        {"title": "Household Hints", "author": None, "etype": "article"},
    ],

    ("Vol7", "No5_May_1920"): [
        {"title": "Suffrage Won by the Mothers of the United States", "author": None, "etype": "article"},
        {"title": "Flowers of Earth and Heaven", "author": None, "etype": "poem"},
        {"title": "Beyond Arsareth", "author": None, "etype": "fiction"},
        {"title": "My Little Span", "author": None, "etype": "poem"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": None, "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],

    ("Vol7", "No6_June_1920"): [
        {"title": "Just Trust", "author": "Julia Farr", "etype": "poem"},
        {"title": "General Conference of the Relief Society", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Beyond Arsareth", "author": "Nephi Anderson", "etype": "fiction"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Child's Right to Happiness", "author": "Ida Smoot Dusenberry", "etype": "article"},
    ],

    ("Vol7", "No7_July_1920"): [
        {"title": "My Son", "author": "Jane Howard", "etype": "poem"},
        {"title": "L. D. S. Relief Society Class for Training Nurses' Aids", "author": "Mrs. Susa Young Gates", "etype": "article"},
        {"title": "Traditions and Customs of the Navajo Indians", "author": "Lucy Gayman Bloomfield", "etype": "article"},
        {"title": "Beyond Arsareth", "author": "Nephi Anderson", "etype": "fiction"},
        {"title": "Hydrotherapy", "author": "Victoria B. Christenson", "etype": "article"},
        {"title": "Blind Authority", "author": "Ida Smoot Dusenberry", "etype": "article"},
        {"title": "A Daughter to Love", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "On the Watchtower", "author": "James H. Anderson", "etype": "article"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],

    ("Vol7", "No8_August_1920"): [
        {"title": "Eulogy to Emmeline B. Wells", "author": "O. F. Ursenbach", "etype": "poem"},
        {"title": "Frontispiece", "author": None, "etype": "article"},
        {"title": "Class in Charities and Relief Work", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "A Vacation and a Rag-bag", "author": "Clara S. Fagergren", "etype": "fiction"},
        {"title": "Temple Work", "author": "Ellen Adair", "etype": "poem"},
        {"title": "A Testimony", "author": "Elder Peter E. Johnson", "etype": "article"},
        {"title": "Am I My Husband's Keeper", "author": "Mary Foster Gibbs", "etype": "article"},
        {"title": "A Victory Dance", "author": None, "etype": "poem"},
        {"title": "The Coming of the Sixth", "author": "Hazel Washburn", "etype": "fiction"},
        {"title": "An Unknown Heroine", "author": None, "etype": "article"},
        {"title": "Household Hints", "author": "Janette A. Hyde", "etype": "article"},
        {"title": "The Grail of the Fields", "author": "Maude Baggarley", "etype": "poem"},
        {"title": "On the Watchtower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Official Round Table", "author": None, "etype": "article"},
        {"title": "Editorial: Who Pays the Price? A Visitor from Across the Sea", "author": None, "etype": "editorial"},
        {"title": "Minutes of Genealogical Convention, Lesson Work Suggestions", "author": None, "etype": "lesson"},
    ],

    ("Vol7", "No9_September_1920"): [
        {"title": "The Needs of Yesterday", "author": "Bertha A. Kleinman", "etype": "poem"},
        {"title": "Mrs. May Wright Sewell", "author": None, "etype": "article"},
        {"title": "Selfish Love", "author": "Mrs. R. A. Madsen", "etype": "article"},
        {"title": "Sacred Vestments of Ancient People", "author": "Susa Young Gates", "etype": "article"},
        {"title": "The Doomsday Book", "author": "Kate Thomas", "etype": "fiction"},
        {"title": "Her Luck", "author": "Clara S. Fagergren", "etype": "fiction"},
        {"title": "Excuses", "author": "Myrtle E. Reeves", "etype": "article"},
        {"title": "The Lost Sheep Returned", "author": "Mary Foster Gibbs", "etype": "article"},
        {"title": "Care of Clothing", "author": None, "etype": "article"},
        {"title": "Summary of Woman's Position in Newly-Enfranchised Countries", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "Editorial", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],

    ("Vol7", "No10_October_1920"): [
        {"title": "What of Thy Victory, O Woman?", "author": "Mary Foster Gibbs", "etype": "poem"},
        {"title": "Testimony of President Emmeline B. Wells", "author": None, "etype": "article"},
        {"title": "A Domestic Drama", "author": "Abagail Howe", "etype": "fiction"},
        {"title": "Household Hints", "author": "Jeanette A. Hyde", "etype": "article"},
        {"title": "On the Watchtower", "author": "James H. Anderson", "etype": "article"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "The Music Page", "author": "Lucy May Green", "etype": "article"},
        {"title": "Norita", "author": "M. M. Warner", "etype": "fiction"},
        {"title": "Editorial: The Deadly Foes of the Night", "author": None, "etype": "editorial"},
        {"title": "Guide Lesson Suggestions", "author": None, "etype": "lesson"},
    ],

    ("Vol7", "No11_November_1920"): [
        {"title": "The Evolution of the Post", "author": None, "etype": "article"},
        {"title": "Heavenly Voices", "author": "Helen Kimball Orgill", "etype": "poem"},
        {"title": "The Better Hubby Contest", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "In the Sunset Glow", "author": "Miss Leah Brown", "etype": "article"},
        {"title": "A Domestic Drama", "author": "Abigail Howe", "etype": "fiction"},
        {"title": "Entertainments for November", "author": "Morag", "etype": "article"},
        {"title": "The Official Round Table", "author": None, "etype": "article"},
        {"title": "On the Watch Tower", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: Let Us Give Thanks", "author": None, "etype": "editorial"},
        {"title": "Lines to An Old Walnut Tree", "author": "Mrs. Donna M. Mecham", "etype": "poem"},
        {"title": "Guide Lesson Suggestions", "author": None, "etype": "lesson"},
        {"title": "The Trumpet Call", "author": "Thelma Nelson", "etype": "poem"},
        {"title": "The Actor", "author": "Grace Ingles Frost", "etype": "poem"},
    ],

    ("Vol7", "No12_December_1920"): [
        {"title": "The Pilgrim Mothers", "author": "Annie Wells Cannon", "etype": "article"},
        {"title": "Utah Descendants of 'Mayflower'", "author": None, "etype": "article"},
        {"title": "Pilgrim Tercentenary Poem", "author": None, "etype": "poem"},
        {"title": "General Conference of Relief Society", "author": None, "etype": "article"},
        {"title": "Relief Society Workers", "author": "Isabelle E. King", "etype": "poem"},
        {"title": "A Domestic Drama", "author": "Abagail Howe", "etype": "fiction"},
        {"title": "Editorial: The Pilgrims Came", "author": None, "etype": "editorial"},
        {"title": "Guide Lesson Suggestions", "author": None, "etype": "lesson"},
        {"title": "Index—Vol. VII", "author": None, "etype": "article"},
    ],
}


# ===================================================================
# VOLUME 8 (1921)
# ===================================================================

VOL8_TOC = {
    ("Vol8", "No1_January_1921"): [
        {"title": "A New Year's Prayer for 1921", "author": None, "etype": "poem"},
        {"title": "Four Great-Grandmothers", "author": None, "etype": "article"},
        {"title": "A Blessed Baby", "author": None, "etype": "article"},
        {"title": "A Prayer", "author": None, "etype": "poem"},
        {"title": "Out of the World", "author": "Susie E.", "etype": "fiction"},
        {"title": "The International Council of Women", "author": None, "etype": "article"},
        {"title": "World Happenings", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": None, "etype": "article"},
        {"title": "Editorial: My New Year Resolution", "author": None, "etype": "editorial"},
        {"title": "Lesson on Tobacco Evil", "author": None, "etype": "lesson"},
        {"title": "Guide Lessons for February", "author": None, "etype": "lesson"},
        {"title": "Guide Lessons for March", "author": None, "etype": "lesson"},
    ],

    ("Vol8", "No2_February_1921"): [
        {"title": "Baby Dear", "author": "Abbie R. Madsen", "etype": "poem"},
        {"title": "The Jerusalem of Today", "author": None, "etype": "article"},
        {"title": "Madame Lydia von F. Mountford", "author": None, "etype": "article"},
        {"title": "From Zion to Jerusalem", "author": None, "etype": "article"},
        {"title": "The Plan of Salvation", "author": "Wilma Stolworthy", "etype": "article"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "Baby Brother", "author": "Abbie R. Madsen", "etype": "poem"},
        {"title": "New Issue of the Book of Mormon", "author": None, "etype": "article"},
        {"title": "The War in Heaven", "author": "Lizzie O. Borgeson White", "etype": "article"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "The Glory of Adversity", "author": "Helen Kimball Orgill", "etype": "poem"},
        {"title": "Editorial: Am I a Failure?", "author": None, "etype": "editorial"},
        {"title": "Birthday of President Emmeline B. Wells", "author": None, "etype": "article"},
        {"title": "Guide Lessons for April", "author": None, "etype": "lesson"},
    ],

    ("Vol8", "No3_March_1921"): [
        {"title": "Mrs. Zina D. Young", "author": None, "etype": "article"},
        {"title": "Return Journey", "author": "Susan Teal Perry", "etype": "article"},
        {"title": "Centennial of President Zina D. Huntington Young", "author": None, "etype": "article"},
        {"title": "Our Anniversary", "author": "Lula L. Greene Richards", "etype": "poem"},
        {"title": "The Primary as First Aid to Relief Society", "author": None, "etype": "article"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "Anniversary Program", "author": "Morag", "etype": "article"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: If I were a Relief Society Teacher", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons for May", "author": None, "etype": "lesson"},
        {"title": "Notes from the Field", "author": None, "etype": "article"},
    ],

    ("Vol8", "No4_April_1921"): [
        {"title": "How Can I Know?", "author": "Bertha A. Kleinman", "etype": "poem"},
        {"title": "Opening of the Chinese Realm for the Preaching of the Gospel", "author": None, "etype": "article"},
        {"title": "European and Near-East Relief Fund", "author": None, "etype": "article"},
        {"title": "Sarah Uses Tact", "author": "Bessie Van Wagonen", "etype": "fiction"},
        {"title": "There are Times", "author": "Helen Kimball Orgill", "etype": "poem"},
        {"title": "From Zion to Jerusalem", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: What About our Clothes?", "author": None, "etype": "editorial"},
        {"title": "Nuts as Daily Food", "author": None, "etype": "article"},
        {"title": "Death of President Anthon H. Lund", "author": None, "etype": "article"},
        {"title": "Birthday Reception for President Emmeline B. Wells", "author": None, "etype": "article"},
        {"title": "Guide Lessons for June", "author": None, "etype": "lesson"},
    ],

    ("Vol8", "No5_May_1921"): [
        {"title": "Motherhood", "author": "C. Byron Whitney", "etype": "poem"},
        {"title": "Chaplet of Mother and Grandmother Verse", "author": None, "etype": "poem"},
        {"title": "Wrapped in Wool", "author": "Agnes Lovendahl", "etype": "fiction"},
        {"title": "The 'Mormon' Church Against Tobacco", "author": "Will H. Brown", "etype": "article"},
        {"title": "The Plan of Mesa Temple", "author": None, "etype": "article"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "Her Testimony", "author": "Zella A. Johnson", "etype": "article"},
        {"title": "About Tobacco", "author": None, "etype": "article"},
        {"title": "The Atonement", "author": "John G. McQuarrie", "etype": "article"},
        {"title": "Belated Joys", "author": "Alveretta Engar", "etype": "poem"},
        {"title": "From Zion to Jerusalem", "author": None, "etype": "article"},
        {"title": "Reorganization of the General Board of the Relief Society", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Criminal Impropriety", "author": None, "etype": "article"},
        {"title": "A Resurrection", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Editorial: The Old Order Changeth", "author": None, "etype": "editorial"},
        {"title": "What Does the Church Owe Me?", "author": None, "etype": "article"},
    ],

    ("Vol8", "No6_June_1921"): [
        {"title": "Death of President Emmeline B. Wells and Appointment of President Clarissa Smith Williams", "author": None, "etype": "article"},
        {"title": "General Conference of Relief Society", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Funeral Services of President Emmeline B. Wells", "author": None, "etype": "article"},
        {"title": "Aunt Em", "author": "Lula Greene Richards", "etype": "poem"},
        {"title": "Relief Society Annual Report", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "Lines", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "The Gospel in Armenia", "author": None, "etype": "article"},
        {"title": "To Mrs. Emmeline B. Wells", "author": "Louise Coulson", "etype": "poem"},
        {"title": "Editorial: Vital Questions", "author": None, "etype": "editorial"},
        {"title": "Book Notices", "author": None, "etype": "article"},
        {"title": "Twilight", "author": "Maud M. Cook", "etype": "poem"},
        {"title": "He Loves Me", "author": "Abbie R. Madsen", "etype": "poem"},
    ],

    ("Vol8", "No7_July_1921"): [
        {"title": "President Clarissa Smith Williams", "author": None, "etype": "article"},
        {"title": "Show Me the Way", "author": "Alice Foutz", "etype": "poem"},
        {"title": "Greeting from the General Presidency of the Relief Society", "author": None, "etype": "article"},
        {"title": "Our New Presidency and General Board", "author": None, "etype": "article"},
        {"title": "Our Music Forces", "author": None, "etype": "article"},
        {"title": "Out of the World", "author": "Milton G. Babcock", "etype": "fiction"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: Our President Emeritus, Emmeline B. Wells", "author": None, "etype": "editorial"},
        {"title": "With the Gift of an Apron", "author": None, "etype": "poem"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],

    ("Vol8", "No8_August_1921"): [
        {"title": "Mme. Curie in her Laboratory in Paris", "author": None, "etype": "article"},
        {"title": "Dethroned", "author": "Bertha A. Kleinman", "etype": "poem"},
        {"title": "Madame Curie", "author": None, "etype": "article"},
        {"title": "Mother's Stories", "author": "Sarah E. Moody", "etype": "fiction"},
        {"title": "Am I Alive?", "author": "C. F. Ursenbach", "etype": "article"},
        {"title": "Out of the World", "author": "Walter G. Babcock", "etype": "fiction"},
        {"title": "From Zion to Jerusalem", "author": None, "etype": "article"},
        {"title": "Hymn of Praise", "author": "Reynold Ahleen", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "The Testing Rod", "author": "Eva Powell", "etype": "article"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "But One Little Talent", "author": "Janey Haefeli", "etype": "article"},
        {"title": "Editorial: Girlhood's Dangers", "author": None, "etype": "editorial"},
        {"title": "Reaping the Reward or Paying the Price", "author": None, "etype": "article"},
        {"title": "Guide Lessons for October", "author": None, "etype": "lesson"},
        {"title": "Manifestations to Mrs. Mary Hyde Woolf", "author": "Zina Y. Card", "etype": "article"},
    ],

    ("Vol8", "No9_September_1921"): [
        {"title": "Elijah Allen and Family", "author": None, "etype": "article"},
        {"title": "Life's Little Day", "author": "Ida R. Alldredge", "etype": "poem"},
        {"title": "Church School Education", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Preserving the Faith of Our Fathers and Mothers", "author": "Adam Bennion", "etype": "article"},
        {"title": "Church Support of Education", "author": "John A. Widtsoe", "etype": "article"},
        {"title": "A Great Church University", "author": "F. S. Harris", "etype": "article"},
        {"title": "The Mothers and the Church Schools", "author": "Zina Young Card", "etype": "article"},
        {"title": "B. Y. U. Family of Educated and Educators", "author": None, "etype": "article"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "From the Watch Tower", "author": "Laura Moench Jenkins", "etype": "article"},
        {"title": "From Zion to Jerusalem", "author": None, "etype": "article"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: No Man Can be Saved in Ignorance", "author": None, "etype": "editorial"},
        {"title": "Who Needs Me?", "author": None, "etype": "poem"},
        {"title": "Dress Reform", "author": None, "etype": "article"},
        {"title": "Guide Lessons for November", "author": None, "etype": "lesson"},
    ],

    ("Vol8", "No10_October_1921"): [
        {"title": "Relief Society Nurse Class", "author": None, "etype": "article"},
        {"title": "The Sum of Life", "author": "Helen Kimball Orgill", "etype": "poem"},
        {"title": "Graduation Exercises Relief Society Nurse Class", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Sweet Singers of Zion", "author": "Edith Ivins Lamoreaux", "etype": "article"},
        {"title": "The Wage of Sin", "author": "Lucy Guyman", "etype": "fiction"},
        {"title": "The New Circular", "author": None, "etype": "article"},
        {"title": "Beautiful Eyes", "author": "Abbie R. Madsen", "etype": "poem"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "In Memory of Utah's First School Teacher", "author": None, "etype": "article"},
        {"title": "The Revelation", "author": "Hannah D. Tomsik", "etype": "article"},
        {"title": "Excursion Salt Lake Temple Workers", "author": None, "etype": "article"},
        {"title": "Relationship of the Child to the Temple", "author": "Clara W. Beebe", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy B. Lyman", "etype": "article"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: Motives or Basis of Judgment", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons for December", "author": None, "etype": "lesson"},
    ],

    ("Vol8", "No11_November_1921"): [
        {"title": "President Heber J. Grant Overlooking Dixie", "author": None, "etype": "article"},
        {"title": "My Dixie Home", "author": "President A. W. Ivins", "etype": "article"},
        {"title": "A Memorable Journey to the Scenic Glories of Southern Utah", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Origin, Object and Destiny of Women", "author": None, "etype": "article"},
        {"title": "Marigold", "author": "Raveina Lundgren", "etype": "fiction"},
        {"title": "The Missionary's Recompense", "author": "Edith Anna Johnson", "etype": "article"},
        {"title": "Don't Let the Baby Forget Me", "author": "L. Lula Greene Richards", "etype": "poem"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "Notes from the Field", "author": "Amy B. Lyman", "etype": "article"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: Sparks Struck from the Conference Fires", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons for January", "author": None, "etype": "lesson"},
    ],

    ("Vol8", "No12_December_1921"): [
        {"title": "General Conference of Relief Society", "author": "Amy Brown Lyman, General Secretary", "etype": "article"},
        {"title": "Out of the World", "author": "G. Milton Babcock", "etype": "fiction"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: The Year's Old Age", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons for February", "author": None, "etype": "lesson"},
        {"title": "Life's Mirror", "author": "Madeline Bridges", "etype": "poem"},
    ],
}


# ===================================================================
# VOLUME 9 (1922)
# ===================================================================

VOL9_TOC = {
    ("Vol9", "No1_January_1922"): [
        {"title": "Presiding Patriarchs", "author": None, "etype": "article"},
        {"title": "Greeting", "author": "General Presidency", "etype": "article"},
        {"title": "Presiding Patriarchs of the Church", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Reminiscences of the Grand-daughter of Hyrum Smith", "author": "Nellie Story Bean", "etype": "article"},
        {"title": "Bubbles and Troubles", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "Disarmament Conference Delegations", "author": None, "etype": "article"},
        {"title": "Book Notices", "author": None, "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy B. Lyman", "etype": "article"},
        {"title": "Conventions and Conferences", "author": None, "etype": "article"},
        {"title": "Reforming Mother", "author": None, "etype": "article"},
        {"title": "Vocational Guidance", "author": "Dr. John T. Miller", "etype": "article"},
        {"title": "Responsibility of Parents in Teaching the Gospel to their Children", "author": "Lucy Wright Snow", "etype": "article"},
        {"title": "The Art of Cookery in the Hotel Utah", "author": None, "etype": "article"},
        {"title": "World Happenings", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: How Do You Do, New Year?", "author": None, "etype": "editorial"},
        {"title": "Week's Study in the Brigham Young University", "author": None, "etype": "article"},
        {"title": "To Stake Teacher-Training Supervisors", "author": None, "etype": "article"},
    ],

    ("Vol9", "No2_February_1922"): [
        {"title": "President Charles W. Penrose", "author": None, "etype": "article"},
        {"title": "Aunt Em's Birthday", "author": "Ruth May Fox", "etype": "poem"},
        {"title": "President Charles W. Penrose", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Views of Jerusalem", "author": "Charles W. Penrose", "etype": "article"},
        {"title": "Who is my Loved One?", "author": "Kate Thomas", "etype": "poem"},
        {"title": "Gambling for the Glory of God", "author": "Milton Bennion", "etype": "article"},
        {"title": "Maternity Bill Passed", "author": None, "etype": "article"},
        {"title": "William Fowler", "author": None, "etype": "article"},
        {"title": "A Prayer of Gratitude", "author": "Matilda K. Galloway", "etype": "poem"},
        {"title": "Bubbles and Troubles", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "The Tate Family", "author": "Margueritte Cregar Lund", "etype": "article"},
        {"title": "World's Destiny in Hands of U. S.", "author": None, "etype": "article"},
        {"title": "Suggestive Program", "author": "Lucy May Green", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "The General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: Jealousy", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons", "author": None, "etype": "lesson"},
    ],

    ("Vol9", "No3_March_1922"): [
        {"title": "Officers of First Relief Society in Denmark", "author": None, "etype": "article"},
        {"title": "The Questions Answered", "author": "Vera Lee Kearl", "etype": "article"},
        {"title": "Relief Society Beginnings in Foreign Lands", "author": None, "etype": "article"},
        {"title": "A Loan", "author": "Kate B. Curtis", "etype": "fiction"},
        {"title": "Alexander Neibaur", "author": "Susa Young Gates", "etype": "article"},
        {"title": "A Mother's Plea", "author": "Louise Gulbransen", "etype": "poem"},
        {"title": "Bubbles and Troubles", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "Uncommon Honesty", "author": "Milton Bennion", "etype": "article"},
        {"title": "I Am Going Back to Father", "author": "Marie Jensen", "etype": "poem"},
        {"title": "Hotel Utah Food Combinations", "author": "Louis J. Theu", "etype": "article"},
        {"title": "Women and the Disarmament Conference", "author": "Nancy A. Leatherwood", "etype": "article"},
        {"title": "Sunshine on the Peak", "author": "Nina B. McKean", "etype": "poem"},
        {"title": "The General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Editorial: Prayer", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons for May", "author": None, "etype": "lesson"},
    ],

    ("Vol9", "No4_April_1922"): [
        {"title": "Relief Society Workers", "author": "Mina Madsen", "etype": "poem"},
        {"title": "Why I am a 'Mormon'", "author": "P. V. Cardon", "etype": "article"},
        {"title": "Relief Society Beginnings in Utah", "author": "Susa Young Gates", "etype": "article"},
        {"title": "Pageant, 'Come, Come, Ye Saints'", "author": None, "etype": "article"},
        {"title": "Jerusalem Redeemed Through the Law of Tithing", "author": None, "etype": "article"},
        {"title": "Bubbles and Troubles", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "The General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Editorial: The Work of the Millennium", "author": None, "etype": "editorial"},
        {"title": "Book Notices", "author": None, "etype": "article"},
        {"title": "Guide Lessons for June", "author": None, "etype": "lesson"},
    ],

    ("Vol9", "No5_May_1922"): [
        {"title": "A Pioneer Mother's Grave on the Prairie", "author": None, "etype": "article"},
        {"title": "Contentment", "author": "Riveina Lundgren", "etype": "poem"},
        {"title": "A Pioneer Mother's Grave on the Platte River", "author": None, "etype": "article"},
        {"title": "May—Mother's Month", "author": None, "etype": "article"},
        {"title": "Mothering", "author": "Elsie C. Carroll", "etype": "poem"},
        {"title": "Mother", "author": "Velora Darger", "etype": "poem"},
        {"title": "O Mother Mine", "author": "Matilda K. Galloway", "etype": "poem"},
        {"title": "Being a Mother", "author": "Genie Mark", "etype": "poem"},
        {"title": "When Dreams Come True", "author": "Linda S. Fletcher", "etype": "poem"},
        {"title": "Life and Death", "author": "Margaret Erickson", "etype": "poem"},
        {"title": "The Form of a Little Child", "author": "Hannah Deady Tomsick", "etype": "poem"},
        {"title": "If You Should Know", "author": "Ruth M. Penrose", "etype": "poem"},
        {"title": "Bubbles and Troubles", "author": "Ruth Moench Bell", "etype": "fiction"},
        {"title": "Unforgotten", "author": None, "etype": "poem"},
        {"title": "Old Fashioned Thrift", "author": "Coral J. Black", "etype": "article"},
        {"title": "Tell it Now", "author": "Bertha A. Kleinman", "etype": "poem"},
        {"title": "The Awakening of Margaret Vorrest", "author": "Ivy Williams Stone", "etype": "fiction"},
        {"title": "Freedom and the Changing Standards", "author": "May Roberts Rinehart", "etype": "article"},
        {"title": "The General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: Just Mothering", "author": None, "etype": "editorial"},
        {"title": "Note", "author": "Nephi Anderson", "etype": "article"},
    ],

    ("Vol9", "No6_June_1922"): [
        {"title": "Relief Society Assembly Hall and Board Meeting Room", "author": None, "etype": "article"},
        {"title": "Keep on the Key", "author": "Joseph H. Dean", "etype": "article"},
        {"title": "General Conference of Relief Society", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Teachers' Topics for July and August", "author": None, "etype": "lesson"},
        {"title": "Editorial: The Measure of Success", "author": None, "etype": "editorial"},
        {"title": "Smoking and Non-Smoking Women", "author": "Will H. Brown", "etype": "article"},
    ],

    ("Vol9", "No7_July_1922"): [
        {"title": "Guests", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Our Hymn Book", "author": "Susa Young Gates", "etype": "article"},
        {"title": "An Indian Story", "author": "Lucy Guyman Bloomfield", "etype": "fiction"},
        {"title": "Trust in God", "author": "Abby K. Robinson", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Parting", "author": "George Careless", "etype": "poem"},
        {"title": "Teacher Training", "author": None, "etype": "lesson"},
        {"title": "Let us Seek Eternal Life", "author": "Reinhard Maeser", "etype": "article"},
        {"title": "Peace", "author": "Rebecca F. Lewis", "etype": "poem"},
        {"title": "The General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "Ann and Her Husband", "author": None, "etype": "fiction"},
        {"title": "Guide Lessons for September", "author": None, "etype": "lesson"},
        {"title": "Your Thirty Slaves", "author": None, "etype": "article"},
    ],

    ("Vol9", "No8_August_1922"): [
        {"title": "A Tribute to Sister Susa Y. Gates", "author": "Ruth May Fox", "etype": "article"},
        {"title": "Our Retiring Editor", "author": None, "etype": "article"},
        {"title": "Golden Wedding of Mr. And Mrs. A. W. McCune", "author": None, "etype": "article"},
        {"title": "Girls in Our Own Zion's Cooperative Mercantile Institution", "author": None, "etype": "article"},
        {"title": "My Baby's Prayer", "author": "Mrs. L. E. Russon", "etype": "poem"},
        {"title": "Notes on Bible Poetry", "author": "L. Lulu Greene Richards", "etype": "article"},
        {"title": "The Ungrateful Indian", "author": "Nina B. McKean", "etype": "fiction"},
        {"title": "The Relief Society Magazine", "author": "Mrs. Christine Stacey", "etype": "article"},
        {"title": "Summer Menus", "author": "Jeanette A. Hyde", "etype": "article"},
        {"title": "Recreative", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "Hotel Utah Food Combinations", "author": "Louis J. Theu", "etype": "article"},
        {"title": "Northern Mexico Recipes", "author": "Gladys Sanders", "etype": "article"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Nature's Perfect Food", "author": "A. A. Hinckley", "etype": "article"},
        {"title": "Your Services to God and Man", "author": "Sarah Deady Tomsik", "etype": "article"},
        {"title": "Editorial: Resignation of Mrs. Susa Young Gates", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons for October", "author": None, "etype": "lesson"},
    ],

    ("Vol9", "No9_September_1922"): [
        {"title": "Pres. Heber J. Grant and Pioneer L. Sobriskie Young", "author": None, "etype": "article"},
        {"title": "This is the Place", "author": "Julia Dare", "etype": "poem"},
        {"title": "The Pioneer Jubilee", "author": "Annie Wells Cannon", "etype": "article"},
        {"title": "Exercises", "author": None, "etype": "article"},
        {"title": "Consolation", "author": "Zella A. Johnson", "etype": "poem"},
        {"title": "The Poorhouse for Mother", "author": "Clara Fagergren", "etype": "fiction"},
        {"title": "A Widow's Prayer", "author": "Hazel S. Washburn", "etype": "poem"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "A Dollar Saved is a Dollar Earned", "author": "Lalene H. Hart", "etype": "article"},
        {"title": "The General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "My Conversion to Work for the Dead", "author": "Nina B. McKean", "etype": "article"},
        {"title": "Editorial: Priesthood", "author": None, "etype": "editorial"},
        {"title": "The International Council of Women to Meet in U. S.", "author": None, "etype": "article"},
        {"title": "Guide Lessons for November", "author": None, "etype": "lesson"},
    ],

    ("Vol9", "No10_October_1922"): [
        {"title": "Cyrus E. Dallin", "author": None, "etype": "article"},
        {"title": "Mutual Appreciation", "author": "Lula Greene Richards", "etype": "poem"},
        {"title": "Dallin's Gift of Massassoit to Utah", "author": "Alice Merrill Horne", "etype": "article"},
        {"title": "Interview with Mrs. Thomas Dallin", "author": "Alice L. Reynolds", "etype": "article"},
        {"title": "Law Enforcement", "author": "Milton Bennion", "etype": "article"},
        {"title": "Aunt Bine", "author": "Myron E. Crandall, Jr.", "etype": "fiction"},
        {"title": "Woman's Privilege", "author": "Ruth Savage Hilton", "etype": "article"},
        {"title": "Leisure", "author": None, "etype": "article"},
        {"title": "Home Economics", "author": "Jeannette A. Hyde", "etype": "article"},
        {"title": "The Last Service", "author": "Annie D. Palmer", "etype": "fiction"},
        {"title": "Notes from the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Attune Your Hearts", "author": "Mrs. Ida R. Alldredge", "etype": "poem"},
        {"title": "A Twisted Holiday", "author": "Lila Little Hicken", "etype": "fiction"},
        {"title": "The General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "Alone", "author": "Bertha Roberts", "etype": "poem"},
        {"title": "Editorial: The Need of the Hour", "author": None, "etype": "editorial"},
        {"title": "Guide Lessons for December", "author": None, "etype": "lesson"},
    ],

    ("Vol9", "No11_November_1922"): [
        {"title": "Bureau of Information, Temple Block", "author": None, "etype": "article"},
        {"title": "Jake Clayton", "author": None, "etype": "fiction"},
        {"title": "The Temple Block Mission", "author": "Levi Edgar Young", "etype": "article"},
        {"title": "Yours is the Right", "author": "Bertha A. Kleinman", "etype": "poem"},
        {"title": "Prohibition Enforcement", "author": "Clarissa S. Williams", "etype": "article"},
        {"title": "A Modern John Alden", "author": "Julia A. F. Lund", "etype": "fiction"},
        {"title": "An Old Time Thanksgiving", "author": "Helen Everston Smith", "etype": "article"},
        {"title": "Be Near Me", "author": "Alice Morrill", "etype": "poem"},
        {"title": "Utah Public Health Conference", "author": None, "etype": "article"},
        {"title": "Integrity—a Noble Word", "author": "Jesma", "etype": "article"},
        {"title": "Pioneer Days", "author": "Laura F. Crane", "etype": "article"},
        {"title": "My Little Friend", "author": "May Booth Talmage", "etype": "article"},
        {"title": "Words", "author": "Grace Ingles Frost", "etype": "poem"},
        {"title": "The General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "Notes From the Field", "author": "Amy Brown Lyman", "etype": "article"},
        {"title": "Editorial: Spiritual Status of Our Present-day World", "author": None, "etype": "editorial"},
        {"title": "Selection", "author": "J. G. Whittier", "etype": "poem"},
        {"title": "Guide Lessons for December", "author": None, "etype": "lesson"},
        {"title": "Salt Lake City's Milk Supply", "author": "Fred W. Merrill", "etype": "article"},
    ],

    ("Vol9", "No12_December_1922"): [
        {"title": "Arrival of the Shepherds", "author": None, "etype": "article"},
        {"title": "For Christmas The Good They Do Depends On You", "author": None, "etype": "article"},
        {"title": "Christmas Giving", "author": "Mary E. Connelly", "etype": "article"},
        {"title": "General Procession", "author": "James H. Anderson", "etype": "article"},
        {"title": "Editorial: The Christmas Spirit", "author": None, "etype": "editorial"},
        {"title": "The Message of the Bells", "author": "Nina Burnham McKean", "etype": "poem"},
    ],
}
